#!/bin/bash
set -euo pipefail
ROOT=${1:-}
[ -d "${ROOT}" ] || { echo "usage: $0 RESULTS_DIR" >&2; exit 2; }
MAIN=${LITELIB_MAIN_DIR:-${HOME}/LiteLib}
OUT="${MAIN}/results/leveldb-overhead/processed"
python3 "$(dirname "$0")/ae_overhead_collect.py" "${ROOT}" --output "${OUT}"
echo "  [ OK ] LevelDB overhead data -> ${OUT}/leveldb.json"
echo "  Figures 15/16 are regenerated by the combined overhead plot command."
