// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAServiceProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HAServiceProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HAServiceProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HAServiceProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HAServiceProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HAServiceProtocol_2eproto;
namespace hadoop {
namespace common {
class GetServiceStatusRequestProto;
struct GetServiceStatusRequestProtoDefaultTypeInternal;
extern GetServiceStatusRequestProtoDefaultTypeInternal _GetServiceStatusRequestProto_default_instance_;
class GetServiceStatusResponseProto;
struct GetServiceStatusResponseProtoDefaultTypeInternal;
extern GetServiceStatusResponseProtoDefaultTypeInternal _GetServiceStatusResponseProto_default_instance_;
class HAStateChangeRequestInfoProto;
struct HAStateChangeRequestInfoProtoDefaultTypeInternal;
extern HAStateChangeRequestInfoProtoDefaultTypeInternal _HAStateChangeRequestInfoProto_default_instance_;
class MonitorHealthRequestProto;
struct MonitorHealthRequestProtoDefaultTypeInternal;
extern MonitorHealthRequestProtoDefaultTypeInternal _MonitorHealthRequestProto_default_instance_;
class MonitorHealthResponseProto;
struct MonitorHealthResponseProtoDefaultTypeInternal;
extern MonitorHealthResponseProtoDefaultTypeInternal _MonitorHealthResponseProto_default_instance_;
class TransitionToActiveRequestProto;
struct TransitionToActiveRequestProtoDefaultTypeInternal;
extern TransitionToActiveRequestProtoDefaultTypeInternal _TransitionToActiveRequestProto_default_instance_;
class TransitionToActiveResponseProto;
struct TransitionToActiveResponseProtoDefaultTypeInternal;
extern TransitionToActiveResponseProtoDefaultTypeInternal _TransitionToActiveResponseProto_default_instance_;
class TransitionToObserverRequestProto;
struct TransitionToObserverRequestProtoDefaultTypeInternal;
extern TransitionToObserverRequestProtoDefaultTypeInternal _TransitionToObserverRequestProto_default_instance_;
class TransitionToObserverResponseProto;
struct TransitionToObserverResponseProtoDefaultTypeInternal;
extern TransitionToObserverResponseProtoDefaultTypeInternal _TransitionToObserverResponseProto_default_instance_;
class TransitionToStandbyRequestProto;
struct TransitionToStandbyRequestProtoDefaultTypeInternal;
extern TransitionToStandbyRequestProtoDefaultTypeInternal _TransitionToStandbyRequestProto_default_instance_;
class TransitionToStandbyResponseProto;
struct TransitionToStandbyResponseProtoDefaultTypeInternal;
extern TransitionToStandbyResponseProtoDefaultTypeInternal _TransitionToStandbyResponseProto_default_instance_;
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> ::hadoop::common::GetServiceStatusRequestProto* Arena::CreateMaybeMessage<::hadoop::common::GetServiceStatusRequestProto>(Arena*);
template<> ::hadoop::common::GetServiceStatusResponseProto* Arena::CreateMaybeMessage<::hadoop::common::GetServiceStatusResponseProto>(Arena*);
template<> ::hadoop::common::HAStateChangeRequestInfoProto* Arena::CreateMaybeMessage<::hadoop::common::HAStateChangeRequestInfoProto>(Arena*);
template<> ::hadoop::common::MonitorHealthRequestProto* Arena::CreateMaybeMessage<::hadoop::common::MonitorHealthRequestProto>(Arena*);
template<> ::hadoop::common::MonitorHealthResponseProto* Arena::CreateMaybeMessage<::hadoop::common::MonitorHealthResponseProto>(Arena*);
template<> ::hadoop::common::TransitionToActiveRequestProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToActiveRequestProto>(Arena*);
template<> ::hadoop::common::TransitionToActiveResponseProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToActiveResponseProto>(Arena*);
template<> ::hadoop::common::TransitionToObserverRequestProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToObserverRequestProto>(Arena*);
template<> ::hadoop::common::TransitionToObserverResponseProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToObserverResponseProto>(Arena*);
template<> ::hadoop::common::TransitionToStandbyRequestProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToStandbyRequestProto>(Arena*);
template<> ::hadoop::common::TransitionToStandbyResponseProto* Arena::CreateMaybeMessage<::hadoop::common::TransitionToStandbyResponseProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hadoop {
namespace common {

enum HAServiceStateProto : int {
  INITIALIZING = 0,
  ACTIVE = 1,
  STANDBY = 2,
  OBSERVER = 3
};
bool HAServiceStateProto_IsValid(int value);
constexpr HAServiceStateProto HAServiceStateProto_MIN = INITIALIZING;
constexpr HAServiceStateProto HAServiceStateProto_MAX = OBSERVER;
constexpr int HAServiceStateProto_ARRAYSIZE = HAServiceStateProto_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HAServiceStateProto_descriptor();
template<typename T>
inline const std::string& HAServiceStateProto_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HAServiceStateProto>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HAServiceStateProto_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HAServiceStateProto_descriptor(), enum_t_value);
}
inline bool HAServiceStateProto_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, HAServiceStateProto* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HAServiceStateProto>(
    HAServiceStateProto_descriptor(), name, value);
}
enum HARequestSource : int {
  REQUEST_BY_USER = 0,
  REQUEST_BY_USER_FORCED = 1,
  REQUEST_BY_ZKFC = 2
};
bool HARequestSource_IsValid(int value);
constexpr HARequestSource HARequestSource_MIN = REQUEST_BY_USER;
constexpr HARequestSource HARequestSource_MAX = REQUEST_BY_ZKFC;
constexpr int HARequestSource_ARRAYSIZE = HARequestSource_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HARequestSource_descriptor();
template<typename T>
inline const std::string& HARequestSource_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HARequestSource>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HARequestSource_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HARequestSource_descriptor(), enum_t_value);
}
inline bool HARequestSource_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, HARequestSource* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HARequestSource>(
    HARequestSource_descriptor(), name, value);
}
// ===================================================================

class HAStateChangeRequestInfoProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.HAStateChangeRequestInfoProto) */ {
 public:
  inline HAStateChangeRequestInfoProto() : HAStateChangeRequestInfoProto(nullptr) {}
  ~HAStateChangeRequestInfoProto() override;
  explicit PROTOBUF_CONSTEXPR HAStateChangeRequestInfoProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HAStateChangeRequestInfoProto(const HAStateChangeRequestInfoProto& from);
  HAStateChangeRequestInfoProto(HAStateChangeRequestInfoProto&& from) noexcept
    : HAStateChangeRequestInfoProto() {
    *this = ::std::move(from);
  }

  inline HAStateChangeRequestInfoProto& operator=(const HAStateChangeRequestInfoProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HAStateChangeRequestInfoProto& operator=(HAStateChangeRequestInfoProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HAStateChangeRequestInfoProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HAStateChangeRequestInfoProto* internal_default_instance() {
    return reinterpret_cast<const HAStateChangeRequestInfoProto*>(
               &_HAStateChangeRequestInfoProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HAStateChangeRequestInfoProto& a, HAStateChangeRequestInfoProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HAStateChangeRequestInfoProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HAStateChangeRequestInfoProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HAStateChangeRequestInfoProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HAStateChangeRequestInfoProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HAStateChangeRequestInfoProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HAStateChangeRequestInfoProto& from) {
    HAStateChangeRequestInfoProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HAStateChangeRequestInfoProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.HAStateChangeRequestInfoProto";
  }
  protected:
  explicit HAStateChangeRequestInfoProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqSourceFieldNumber = 1,
  };
  // required .hadoop.common.HARequestSource reqSource = 1;
  bool has_reqsource() const;
  private:
  bool _internal_has_reqsource() const;
  public:
  void clear_reqsource();
  ::hadoop::common::HARequestSource reqsource() const;
  void set_reqsource(::hadoop::common::HARequestSource value);
  private:
  ::hadoop::common::HARequestSource _internal_reqsource() const;
  void _internal_set_reqsource(::hadoop::common::HARequestSource value);
  public:

  // @@protoc_insertion_point(class_scope:hadoop.common.HAStateChangeRequestInfoProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int reqsource_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class MonitorHealthRequestProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.MonitorHealthRequestProto) */ {
 public:
  inline MonitorHealthRequestProto() : MonitorHealthRequestProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR MonitorHealthRequestProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MonitorHealthRequestProto(const MonitorHealthRequestProto& from);
  MonitorHealthRequestProto(MonitorHealthRequestProto&& from) noexcept
    : MonitorHealthRequestProto() {
    *this = ::std::move(from);
  }

  inline MonitorHealthRequestProto& operator=(const MonitorHealthRequestProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MonitorHealthRequestProto& operator=(MonitorHealthRequestProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MonitorHealthRequestProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const MonitorHealthRequestProto* internal_default_instance() {
    return reinterpret_cast<const MonitorHealthRequestProto*>(
               &_MonitorHealthRequestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MonitorHealthRequestProto& a, MonitorHealthRequestProto& b) {
    a.Swap(&b);
  }
  inline void Swap(MonitorHealthRequestProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MonitorHealthRequestProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MonitorHealthRequestProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MonitorHealthRequestProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const MonitorHealthRequestProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const MonitorHealthRequestProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.MonitorHealthRequestProto";
  }
  protected:
  explicit MonitorHealthRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.MonitorHealthRequestProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class MonitorHealthResponseProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.MonitorHealthResponseProto) */ {
 public:
  inline MonitorHealthResponseProto() : MonitorHealthResponseProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR MonitorHealthResponseProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MonitorHealthResponseProto(const MonitorHealthResponseProto& from);
  MonitorHealthResponseProto(MonitorHealthResponseProto&& from) noexcept
    : MonitorHealthResponseProto() {
    *this = ::std::move(from);
  }

  inline MonitorHealthResponseProto& operator=(const MonitorHealthResponseProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MonitorHealthResponseProto& operator=(MonitorHealthResponseProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MonitorHealthResponseProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const MonitorHealthResponseProto* internal_default_instance() {
    return reinterpret_cast<const MonitorHealthResponseProto*>(
               &_MonitorHealthResponseProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MonitorHealthResponseProto& a, MonitorHealthResponseProto& b) {
    a.Swap(&b);
  }
  inline void Swap(MonitorHealthResponseProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MonitorHealthResponseProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MonitorHealthResponseProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MonitorHealthResponseProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const MonitorHealthResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const MonitorHealthResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.MonitorHealthResponseProto";
  }
  protected:
  explicit MonitorHealthResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.MonitorHealthResponseProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToActiveRequestProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToActiveRequestProto) */ {
 public:
  inline TransitionToActiveRequestProto() : TransitionToActiveRequestProto(nullptr) {}
  ~TransitionToActiveRequestProto() override;
  explicit PROTOBUF_CONSTEXPR TransitionToActiveRequestProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToActiveRequestProto(const TransitionToActiveRequestProto& from);
  TransitionToActiveRequestProto(TransitionToActiveRequestProto&& from) noexcept
    : TransitionToActiveRequestProto() {
    *this = ::std::move(from);
  }

  inline TransitionToActiveRequestProto& operator=(const TransitionToActiveRequestProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToActiveRequestProto& operator=(TransitionToActiveRequestProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToActiveRequestProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToActiveRequestProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToActiveRequestProto*>(
               &_TransitionToActiveRequestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TransitionToActiveRequestProto& a, TransitionToActiveRequestProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToActiveRequestProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToActiveRequestProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToActiveRequestProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToActiveRequestProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransitionToActiveRequestProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransitionToActiveRequestProto& from) {
    TransitionToActiveRequestProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransitionToActiveRequestProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToActiveRequestProto";
  }
  protected:
  explicit TransitionToActiveRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqInfoFieldNumber = 1,
  };
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  bool has_reqinfo() const;
  private:
  bool _internal_has_reqinfo() const;
  public:
  void clear_reqinfo();
  const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo() const;
  PROTOBUF_NODISCARD ::hadoop::common::HAStateChangeRequestInfoProto* release_reqinfo();
  ::hadoop::common::HAStateChangeRequestInfoProto* mutable_reqinfo();
  void set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  private:
  const ::hadoop::common::HAStateChangeRequestInfoProto& _internal_reqinfo() const;
  ::hadoop::common::HAStateChangeRequestInfoProto* _internal_mutable_reqinfo();
  public:
  void unsafe_arena_set_allocated_reqinfo(
      ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  ::hadoop::common::HAStateChangeRequestInfoProto* unsafe_arena_release_reqinfo();

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToActiveRequestProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToActiveResponseProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToActiveResponseProto) */ {
 public:
  inline TransitionToActiveResponseProto() : TransitionToActiveResponseProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR TransitionToActiveResponseProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToActiveResponseProto(const TransitionToActiveResponseProto& from);
  TransitionToActiveResponseProto(TransitionToActiveResponseProto&& from) noexcept
    : TransitionToActiveResponseProto() {
    *this = ::std::move(from);
  }

  inline TransitionToActiveResponseProto& operator=(const TransitionToActiveResponseProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToActiveResponseProto& operator=(TransitionToActiveResponseProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToActiveResponseProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToActiveResponseProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToActiveResponseProto*>(
               &_TransitionToActiveResponseProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TransitionToActiveResponseProto& a, TransitionToActiveResponseProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToActiveResponseProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToActiveResponseProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToActiveResponseProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToActiveResponseProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const TransitionToActiveResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const TransitionToActiveResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToActiveResponseProto";
  }
  protected:
  explicit TransitionToActiveResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToActiveResponseProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToStandbyRequestProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToStandbyRequestProto) */ {
 public:
  inline TransitionToStandbyRequestProto() : TransitionToStandbyRequestProto(nullptr) {}
  ~TransitionToStandbyRequestProto() override;
  explicit PROTOBUF_CONSTEXPR TransitionToStandbyRequestProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToStandbyRequestProto(const TransitionToStandbyRequestProto& from);
  TransitionToStandbyRequestProto(TransitionToStandbyRequestProto&& from) noexcept
    : TransitionToStandbyRequestProto() {
    *this = ::std::move(from);
  }

  inline TransitionToStandbyRequestProto& operator=(const TransitionToStandbyRequestProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToStandbyRequestProto& operator=(TransitionToStandbyRequestProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToStandbyRequestProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToStandbyRequestProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToStandbyRequestProto*>(
               &_TransitionToStandbyRequestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(TransitionToStandbyRequestProto& a, TransitionToStandbyRequestProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToStandbyRequestProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToStandbyRequestProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToStandbyRequestProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToStandbyRequestProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransitionToStandbyRequestProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransitionToStandbyRequestProto& from) {
    TransitionToStandbyRequestProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransitionToStandbyRequestProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToStandbyRequestProto";
  }
  protected:
  explicit TransitionToStandbyRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqInfoFieldNumber = 1,
  };
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  bool has_reqinfo() const;
  private:
  bool _internal_has_reqinfo() const;
  public:
  void clear_reqinfo();
  const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo() const;
  PROTOBUF_NODISCARD ::hadoop::common::HAStateChangeRequestInfoProto* release_reqinfo();
  ::hadoop::common::HAStateChangeRequestInfoProto* mutable_reqinfo();
  void set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  private:
  const ::hadoop::common::HAStateChangeRequestInfoProto& _internal_reqinfo() const;
  ::hadoop::common::HAStateChangeRequestInfoProto* _internal_mutable_reqinfo();
  public:
  void unsafe_arena_set_allocated_reqinfo(
      ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  ::hadoop::common::HAStateChangeRequestInfoProto* unsafe_arena_release_reqinfo();

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToStandbyRequestProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToStandbyResponseProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToStandbyResponseProto) */ {
 public:
  inline TransitionToStandbyResponseProto() : TransitionToStandbyResponseProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR TransitionToStandbyResponseProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToStandbyResponseProto(const TransitionToStandbyResponseProto& from);
  TransitionToStandbyResponseProto(TransitionToStandbyResponseProto&& from) noexcept
    : TransitionToStandbyResponseProto() {
    *this = ::std::move(from);
  }

  inline TransitionToStandbyResponseProto& operator=(const TransitionToStandbyResponseProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToStandbyResponseProto& operator=(TransitionToStandbyResponseProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToStandbyResponseProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToStandbyResponseProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToStandbyResponseProto*>(
               &_TransitionToStandbyResponseProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(TransitionToStandbyResponseProto& a, TransitionToStandbyResponseProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToStandbyResponseProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToStandbyResponseProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToStandbyResponseProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToStandbyResponseProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const TransitionToStandbyResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const TransitionToStandbyResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToStandbyResponseProto";
  }
  protected:
  explicit TransitionToStandbyResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToStandbyResponseProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToObserverRequestProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToObserverRequestProto) */ {
 public:
  inline TransitionToObserverRequestProto() : TransitionToObserverRequestProto(nullptr) {}
  ~TransitionToObserverRequestProto() override;
  explicit PROTOBUF_CONSTEXPR TransitionToObserverRequestProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToObserverRequestProto(const TransitionToObserverRequestProto& from);
  TransitionToObserverRequestProto(TransitionToObserverRequestProto&& from) noexcept
    : TransitionToObserverRequestProto() {
    *this = ::std::move(from);
  }

  inline TransitionToObserverRequestProto& operator=(const TransitionToObserverRequestProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToObserverRequestProto& operator=(TransitionToObserverRequestProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToObserverRequestProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToObserverRequestProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToObserverRequestProto*>(
               &_TransitionToObserverRequestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(TransitionToObserverRequestProto& a, TransitionToObserverRequestProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToObserverRequestProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToObserverRequestProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToObserverRequestProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToObserverRequestProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransitionToObserverRequestProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransitionToObserverRequestProto& from) {
    TransitionToObserverRequestProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransitionToObserverRequestProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToObserverRequestProto";
  }
  protected:
  explicit TransitionToObserverRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqInfoFieldNumber = 1,
  };
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  bool has_reqinfo() const;
  private:
  bool _internal_has_reqinfo() const;
  public:
  void clear_reqinfo();
  const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo() const;
  PROTOBUF_NODISCARD ::hadoop::common::HAStateChangeRequestInfoProto* release_reqinfo();
  ::hadoop::common::HAStateChangeRequestInfoProto* mutable_reqinfo();
  void set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  private:
  const ::hadoop::common::HAStateChangeRequestInfoProto& _internal_reqinfo() const;
  ::hadoop::common::HAStateChangeRequestInfoProto* _internal_mutable_reqinfo();
  public:
  void unsafe_arena_set_allocated_reqinfo(
      ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo);
  ::hadoop::common::HAStateChangeRequestInfoProto* unsafe_arena_release_reqinfo();

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToObserverRequestProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class TransitionToObserverResponseProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.TransitionToObserverResponseProto) */ {
 public:
  inline TransitionToObserverResponseProto() : TransitionToObserverResponseProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR TransitionToObserverResponseProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransitionToObserverResponseProto(const TransitionToObserverResponseProto& from);
  TransitionToObserverResponseProto(TransitionToObserverResponseProto&& from) noexcept
    : TransitionToObserverResponseProto() {
    *this = ::std::move(from);
  }

  inline TransitionToObserverResponseProto& operator=(const TransitionToObserverResponseProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransitionToObserverResponseProto& operator=(TransitionToObserverResponseProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransitionToObserverResponseProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransitionToObserverResponseProto* internal_default_instance() {
    return reinterpret_cast<const TransitionToObserverResponseProto*>(
               &_TransitionToObserverResponseProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(TransitionToObserverResponseProto& a, TransitionToObserverResponseProto& b) {
    a.Swap(&b);
  }
  inline void Swap(TransitionToObserverResponseProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransitionToObserverResponseProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransitionToObserverResponseProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransitionToObserverResponseProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const TransitionToObserverResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const TransitionToObserverResponseProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.TransitionToObserverResponseProto";
  }
  protected:
  explicit TransitionToObserverResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.TransitionToObserverResponseProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class GetServiceStatusRequestProto final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hadoop.common.GetServiceStatusRequestProto) */ {
 public:
  inline GetServiceStatusRequestProto() : GetServiceStatusRequestProto(nullptr) {}
  explicit PROTOBUF_CONSTEXPR GetServiceStatusRequestProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServiceStatusRequestProto(const GetServiceStatusRequestProto& from);
  GetServiceStatusRequestProto(GetServiceStatusRequestProto&& from) noexcept
    : GetServiceStatusRequestProto() {
    *this = ::std::move(from);
  }

  inline GetServiceStatusRequestProto& operator=(const GetServiceStatusRequestProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceStatusRequestProto& operator=(GetServiceStatusRequestProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceStatusRequestProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceStatusRequestProto* internal_default_instance() {
    return reinterpret_cast<const GetServiceStatusRequestProto*>(
               &_GetServiceStatusRequestProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(GetServiceStatusRequestProto& a, GetServiceStatusRequestProto& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceStatusRequestProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceStatusRequestProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceStatusRequestProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServiceStatusRequestProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetServiceStatusRequestProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetServiceStatusRequestProto& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.GetServiceStatusRequestProto";
  }
  protected:
  explicit GetServiceStatusRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hadoop.common.GetServiceStatusRequestProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// -------------------------------------------------------------------

class GetServiceStatusResponseProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.GetServiceStatusResponseProto) */ {
 public:
  inline GetServiceStatusResponseProto() : GetServiceStatusResponseProto(nullptr) {}
  ~GetServiceStatusResponseProto() override;
  explicit PROTOBUF_CONSTEXPR GetServiceStatusResponseProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServiceStatusResponseProto(const GetServiceStatusResponseProto& from);
  GetServiceStatusResponseProto(GetServiceStatusResponseProto&& from) noexcept
    : GetServiceStatusResponseProto() {
    *this = ::std::move(from);
  }

  inline GetServiceStatusResponseProto& operator=(const GetServiceStatusResponseProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceStatusResponseProto& operator=(GetServiceStatusResponseProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceStatusResponseProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceStatusResponseProto* internal_default_instance() {
    return reinterpret_cast<const GetServiceStatusResponseProto*>(
               &_GetServiceStatusResponseProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(GetServiceStatusResponseProto& a, GetServiceStatusResponseProto& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceStatusResponseProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceStatusResponseProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceStatusResponseProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServiceStatusResponseProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetServiceStatusResponseProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetServiceStatusResponseProto& from) {
    GetServiceStatusResponseProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceStatusResponseProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.GetServiceStatusResponseProto";
  }
  protected:
  explicit GetServiceStatusResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNotReadyReasonFieldNumber = 3,
    kStateFieldNumber = 1,
    kReadyToBecomeActiveFieldNumber = 2,
  };
  // optional string notReadyReason = 3;
  bool has_notreadyreason() const;
  private:
  bool _internal_has_notreadyreason() const;
  public:
  void clear_notreadyreason();
  const std::string& notreadyreason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_notreadyreason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_notreadyreason();
  PROTOBUF_NODISCARD std::string* release_notreadyreason();
  void set_allocated_notreadyreason(std::string* notreadyreason);
  private:
  const std::string& _internal_notreadyreason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_notreadyreason(const std::string& value);
  std::string* _internal_mutable_notreadyreason();
  public:

  // required .hadoop.common.HAServiceStateProto state = 1;
  bool has_state() const;
  private:
  bool _internal_has_state() const;
  public:
  void clear_state();
  ::hadoop::common::HAServiceStateProto state() const;
  void set_state(::hadoop::common::HAServiceStateProto value);
  private:
  ::hadoop::common::HAServiceStateProto _internal_state() const;
  void _internal_set_state(::hadoop::common::HAServiceStateProto value);
  public:

  // optional bool readyToBecomeActive = 2;
  bool has_readytobecomeactive() const;
  private:
  bool _internal_has_readytobecomeactive() const;
  public:
  void clear_readytobecomeactive();
  bool readytobecomeactive() const;
  void set_readytobecomeactive(bool value);
  private:
  bool _internal_readytobecomeactive() const;
  void _internal_set_readytobecomeactive(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hadoop.common.GetServiceStatusResponseProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr notreadyreason_;
    int state_;
    bool readytobecomeactive_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HAServiceProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HAStateChangeRequestInfoProto

// required .hadoop.common.HARequestSource reqSource = 1;
inline bool HAStateChangeRequestInfoProto::_internal_has_reqsource() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool HAStateChangeRequestInfoProto::has_reqsource() const {
  return _internal_has_reqsource();
}
inline void HAStateChangeRequestInfoProto::clear_reqsource() {
  _impl_.reqsource_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::hadoop::common::HARequestSource HAStateChangeRequestInfoProto::_internal_reqsource() const {
  return static_cast< ::hadoop::common::HARequestSource >(_impl_.reqsource_);
}
inline ::hadoop::common::HARequestSource HAStateChangeRequestInfoProto::reqsource() const {
  // @@protoc_insertion_point(field_get:hadoop.common.HAStateChangeRequestInfoProto.reqSource)
  return _internal_reqsource();
}
inline void HAStateChangeRequestInfoProto::_internal_set_reqsource(::hadoop::common::HARequestSource value) {
  assert(::hadoop::common::HARequestSource_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.reqsource_ = value;
}
inline void HAStateChangeRequestInfoProto::set_reqsource(::hadoop::common::HARequestSource value) {
  _internal_set_reqsource(value);
  // @@protoc_insertion_point(field_set:hadoop.common.HAStateChangeRequestInfoProto.reqSource)
}

// -------------------------------------------------------------------

// MonitorHealthRequestProto

// -------------------------------------------------------------------

// MonitorHealthResponseProto

// -------------------------------------------------------------------

// TransitionToActiveRequestProto

// required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
inline bool TransitionToActiveRequestProto::_internal_has_reqinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.reqinfo_ != nullptr);
  return value;
}
inline bool TransitionToActiveRequestProto::has_reqinfo() const {
  return _internal_has_reqinfo();
}
inline void TransitionToActiveRequestProto::clear_reqinfo() {
  if (_impl_.reqinfo_ != nullptr) _impl_.reqinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToActiveRequestProto::_internal_reqinfo() const {
  const ::hadoop::common::HAStateChangeRequestInfoProto* p = _impl_.reqinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::hadoop::common::HAStateChangeRequestInfoProto&>(
      ::hadoop::common::_HAStateChangeRequestInfoProto_default_instance_);
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToActiveRequestProto::reqinfo() const {
  // @@protoc_insertion_point(field_get:hadoop.common.TransitionToActiveRequestProto.reqInfo)
  return _internal_reqinfo();
}
inline void TransitionToActiveRequestProto::unsafe_arena_set_allocated_reqinfo(
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.reqinfo_);
  }
  _impl_.reqinfo_ = reqinfo;
  if (reqinfo) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.TransitionToActiveRequestProto.reqInfo)
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToActiveRequestProto::release_reqinfo() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToActiveRequestProto::unsafe_arena_release_reqinfo() {
  // @@protoc_insertion_point(field_release:hadoop.common.TransitionToActiveRequestProto.reqInfo)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToActiveRequestProto::_internal_mutable_reqinfo() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.reqinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::hadoop::common::HAStateChangeRequestInfoProto>(GetArenaForAllocation());
    _impl_.reqinfo_ = p;
  }
  return _impl_.reqinfo_;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToActiveRequestProto::mutable_reqinfo() {
  ::hadoop::common::HAStateChangeRequestInfoProto* _msg = _internal_mutable_reqinfo();
  // @@protoc_insertion_point(field_mutable:hadoop.common.TransitionToActiveRequestProto.reqInfo)
  return _msg;
}
inline void TransitionToActiveRequestProto::set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.reqinfo_;
  }
  if (reqinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(reqinfo);
    if (message_arena != submessage_arena) {
      reqinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reqinfo, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reqinfo_ = reqinfo;
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.TransitionToActiveRequestProto.reqInfo)
}

// -------------------------------------------------------------------

// TransitionToActiveResponseProto

// -------------------------------------------------------------------

// TransitionToStandbyRequestProto

// required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
inline bool TransitionToStandbyRequestProto::_internal_has_reqinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.reqinfo_ != nullptr);
  return value;
}
inline bool TransitionToStandbyRequestProto::has_reqinfo() const {
  return _internal_has_reqinfo();
}
inline void TransitionToStandbyRequestProto::clear_reqinfo() {
  if (_impl_.reqinfo_ != nullptr) _impl_.reqinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToStandbyRequestProto::_internal_reqinfo() const {
  const ::hadoop::common::HAStateChangeRequestInfoProto* p = _impl_.reqinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::hadoop::common::HAStateChangeRequestInfoProto&>(
      ::hadoop::common::_HAStateChangeRequestInfoProto_default_instance_);
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToStandbyRequestProto::reqinfo() const {
  // @@protoc_insertion_point(field_get:hadoop.common.TransitionToStandbyRequestProto.reqInfo)
  return _internal_reqinfo();
}
inline void TransitionToStandbyRequestProto::unsafe_arena_set_allocated_reqinfo(
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.reqinfo_);
  }
  _impl_.reqinfo_ = reqinfo;
  if (reqinfo) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.TransitionToStandbyRequestProto.reqInfo)
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToStandbyRequestProto::release_reqinfo() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToStandbyRequestProto::unsafe_arena_release_reqinfo() {
  // @@protoc_insertion_point(field_release:hadoop.common.TransitionToStandbyRequestProto.reqInfo)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToStandbyRequestProto::_internal_mutable_reqinfo() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.reqinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::hadoop::common::HAStateChangeRequestInfoProto>(GetArenaForAllocation());
    _impl_.reqinfo_ = p;
  }
  return _impl_.reqinfo_;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToStandbyRequestProto::mutable_reqinfo() {
  ::hadoop::common::HAStateChangeRequestInfoProto* _msg = _internal_mutable_reqinfo();
  // @@protoc_insertion_point(field_mutable:hadoop.common.TransitionToStandbyRequestProto.reqInfo)
  return _msg;
}
inline void TransitionToStandbyRequestProto::set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.reqinfo_;
  }
  if (reqinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(reqinfo);
    if (message_arena != submessage_arena) {
      reqinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reqinfo, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reqinfo_ = reqinfo;
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.TransitionToStandbyRequestProto.reqInfo)
}

// -------------------------------------------------------------------

// TransitionToStandbyResponseProto

// -------------------------------------------------------------------

// TransitionToObserverRequestProto

// required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
inline bool TransitionToObserverRequestProto::_internal_has_reqinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.reqinfo_ != nullptr);
  return value;
}
inline bool TransitionToObserverRequestProto::has_reqinfo() const {
  return _internal_has_reqinfo();
}
inline void TransitionToObserverRequestProto::clear_reqinfo() {
  if (_impl_.reqinfo_ != nullptr) _impl_.reqinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToObserverRequestProto::_internal_reqinfo() const {
  const ::hadoop::common::HAStateChangeRequestInfoProto* p = _impl_.reqinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::hadoop::common::HAStateChangeRequestInfoProto&>(
      ::hadoop::common::_HAStateChangeRequestInfoProto_default_instance_);
}
inline const ::hadoop::common::HAStateChangeRequestInfoProto& TransitionToObserverRequestProto::reqinfo() const {
  // @@protoc_insertion_point(field_get:hadoop.common.TransitionToObserverRequestProto.reqInfo)
  return _internal_reqinfo();
}
inline void TransitionToObserverRequestProto::unsafe_arena_set_allocated_reqinfo(
    ::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.reqinfo_);
  }
  _impl_.reqinfo_ = reqinfo;
  if (reqinfo) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.TransitionToObserverRequestProto.reqInfo)
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToObserverRequestProto::release_reqinfo() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToObserverRequestProto::unsafe_arena_release_reqinfo() {
  // @@protoc_insertion_point(field_release:hadoop.common.TransitionToObserverRequestProto.reqInfo)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::hadoop::common::HAStateChangeRequestInfoProto* temp = _impl_.reqinfo_;
  _impl_.reqinfo_ = nullptr;
  return temp;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToObserverRequestProto::_internal_mutable_reqinfo() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.reqinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::hadoop::common::HAStateChangeRequestInfoProto>(GetArenaForAllocation());
    _impl_.reqinfo_ = p;
  }
  return _impl_.reqinfo_;
}
inline ::hadoop::common::HAStateChangeRequestInfoProto* TransitionToObserverRequestProto::mutable_reqinfo() {
  ::hadoop::common::HAStateChangeRequestInfoProto* _msg = _internal_mutable_reqinfo();
  // @@protoc_insertion_point(field_mutable:hadoop.common.TransitionToObserverRequestProto.reqInfo)
  return _msg;
}
inline void TransitionToObserverRequestProto::set_allocated_reqinfo(::hadoop::common::HAStateChangeRequestInfoProto* reqinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.reqinfo_;
  }
  if (reqinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(reqinfo);
    if (message_arena != submessage_arena) {
      reqinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reqinfo, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reqinfo_ = reqinfo;
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.TransitionToObserverRequestProto.reqInfo)
}

// -------------------------------------------------------------------

// TransitionToObserverResponseProto

// -------------------------------------------------------------------

// GetServiceStatusRequestProto

// -------------------------------------------------------------------

// GetServiceStatusResponseProto

// required .hadoop.common.HAServiceStateProto state = 1;
inline bool GetServiceStatusResponseProto::_internal_has_state() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool GetServiceStatusResponseProto::has_state() const {
  return _internal_has_state();
}
inline void GetServiceStatusResponseProto::clear_state() {
  _impl_.state_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::hadoop::common::HAServiceStateProto GetServiceStatusResponseProto::_internal_state() const {
  return static_cast< ::hadoop::common::HAServiceStateProto >(_impl_.state_);
}
inline ::hadoop::common::HAServiceStateProto GetServiceStatusResponseProto::state() const {
  // @@protoc_insertion_point(field_get:hadoop.common.GetServiceStatusResponseProto.state)
  return _internal_state();
}
inline void GetServiceStatusResponseProto::_internal_set_state(::hadoop::common::HAServiceStateProto value) {
  assert(::hadoop::common::HAServiceStateProto_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.state_ = value;
}
inline void GetServiceStatusResponseProto::set_state(::hadoop::common::HAServiceStateProto value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:hadoop.common.GetServiceStatusResponseProto.state)
}

// optional bool readyToBecomeActive = 2;
inline bool GetServiceStatusResponseProto::_internal_has_readytobecomeactive() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool GetServiceStatusResponseProto::has_readytobecomeactive() const {
  return _internal_has_readytobecomeactive();
}
inline void GetServiceStatusResponseProto::clear_readytobecomeactive() {
  _impl_.readytobecomeactive_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool GetServiceStatusResponseProto::_internal_readytobecomeactive() const {
  return _impl_.readytobecomeactive_;
}
inline bool GetServiceStatusResponseProto::readytobecomeactive() const {
  // @@protoc_insertion_point(field_get:hadoop.common.GetServiceStatusResponseProto.readyToBecomeActive)
  return _internal_readytobecomeactive();
}
inline void GetServiceStatusResponseProto::_internal_set_readytobecomeactive(bool value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.readytobecomeactive_ = value;
}
inline void GetServiceStatusResponseProto::set_readytobecomeactive(bool value) {
  _internal_set_readytobecomeactive(value);
  // @@protoc_insertion_point(field_set:hadoop.common.GetServiceStatusResponseProto.readyToBecomeActive)
}

// optional string notReadyReason = 3;
inline bool GetServiceStatusResponseProto::_internal_has_notreadyreason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GetServiceStatusResponseProto::has_notreadyreason() const {
  return _internal_has_notreadyreason();
}
inline void GetServiceStatusResponseProto::clear_notreadyreason() {
  _impl_.notreadyreason_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GetServiceStatusResponseProto::notreadyreason() const {
  // @@protoc_insertion_point(field_get:hadoop.common.GetServiceStatusResponseProto.notReadyReason)
  return _internal_notreadyreason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetServiceStatusResponseProto::set_notreadyreason(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.notreadyreason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.GetServiceStatusResponseProto.notReadyReason)
}
inline std::string* GetServiceStatusResponseProto::mutable_notreadyreason() {
  std::string* _s = _internal_mutable_notreadyreason();
  // @@protoc_insertion_point(field_mutable:hadoop.common.GetServiceStatusResponseProto.notReadyReason)
  return _s;
}
inline const std::string& GetServiceStatusResponseProto::_internal_notreadyreason() const {
  return _impl_.notreadyreason_.Get();
}
inline void GetServiceStatusResponseProto::_internal_set_notreadyreason(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.notreadyreason_.Set(value, GetArenaForAllocation());
}
inline std::string* GetServiceStatusResponseProto::_internal_mutable_notreadyreason() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.notreadyreason_.Mutable(GetArenaForAllocation());
}
inline std::string* GetServiceStatusResponseProto::release_notreadyreason() {
  // @@protoc_insertion_point(field_release:hadoop.common.GetServiceStatusResponseProto.notReadyReason)
  if (!_internal_has_notreadyreason()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.notreadyreason_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.notreadyreason_.IsDefault()) {
    _impl_.notreadyreason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void GetServiceStatusResponseProto::set_allocated_notreadyreason(std::string* notreadyreason) {
  if (notreadyreason != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.notreadyreason_.SetAllocated(notreadyreason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.notreadyreason_.IsDefault()) {
    _impl_.notreadyreason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.GetServiceStatusResponseProto.notReadyReason)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace hadoop

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::hadoop::common::HAServiceStateProto> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hadoop::common::HAServiceStateProto>() {
  return ::hadoop::common::HAServiceStateProto_descriptor();
}
template <> struct is_proto_enum< ::hadoop::common::HARequestSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hadoop::common::HARequestSource>() {
  return ::hadoop::common::HARequestSource_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HAServiceProtocol_2eproto
