// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HAServiceProtocol.proto

#include "HAServiceProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hadoop {
namespace common {
PROTOBUF_CONSTEXPR HAStateChangeRequestInfoProto::HAStateChangeRequestInfoProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.reqsource_)*/0} {}
struct HAStateChangeRequestInfoProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HAStateChangeRequestInfoProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HAStateChangeRequestInfoProtoDefaultTypeInternal() {}
  union {
    HAStateChangeRequestInfoProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HAStateChangeRequestInfoProtoDefaultTypeInternal _HAStateChangeRequestInfoProto_default_instance_;
PROTOBUF_CONSTEXPR MonitorHealthRequestProto::MonitorHealthRequestProto(
    ::_pbi::ConstantInitialized) {}
struct MonitorHealthRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MonitorHealthRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MonitorHealthRequestProtoDefaultTypeInternal() {}
  union {
    MonitorHealthRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MonitorHealthRequestProtoDefaultTypeInternal _MonitorHealthRequestProto_default_instance_;
PROTOBUF_CONSTEXPR MonitorHealthResponseProto::MonitorHealthResponseProto(
    ::_pbi::ConstantInitialized) {}
struct MonitorHealthResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MonitorHealthResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MonitorHealthResponseProtoDefaultTypeInternal() {}
  union {
    MonitorHealthResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MonitorHealthResponseProtoDefaultTypeInternal _MonitorHealthResponseProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToActiveRequestProto::TransitionToActiveRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.reqinfo_)*/nullptr} {}
struct TransitionToActiveRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToActiveRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToActiveRequestProtoDefaultTypeInternal() {}
  union {
    TransitionToActiveRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToActiveRequestProtoDefaultTypeInternal _TransitionToActiveRequestProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToActiveResponseProto::TransitionToActiveResponseProto(
    ::_pbi::ConstantInitialized) {}
struct TransitionToActiveResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToActiveResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToActiveResponseProtoDefaultTypeInternal() {}
  union {
    TransitionToActiveResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToActiveResponseProtoDefaultTypeInternal _TransitionToActiveResponseProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToStandbyRequestProto::TransitionToStandbyRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.reqinfo_)*/nullptr} {}
struct TransitionToStandbyRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToStandbyRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToStandbyRequestProtoDefaultTypeInternal() {}
  union {
    TransitionToStandbyRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToStandbyRequestProtoDefaultTypeInternal _TransitionToStandbyRequestProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToStandbyResponseProto::TransitionToStandbyResponseProto(
    ::_pbi::ConstantInitialized) {}
struct TransitionToStandbyResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToStandbyResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToStandbyResponseProtoDefaultTypeInternal() {}
  union {
    TransitionToStandbyResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToStandbyResponseProtoDefaultTypeInternal _TransitionToStandbyResponseProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToObserverRequestProto::TransitionToObserverRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.reqinfo_)*/nullptr} {}
struct TransitionToObserverRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToObserverRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToObserverRequestProtoDefaultTypeInternal() {}
  union {
    TransitionToObserverRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToObserverRequestProtoDefaultTypeInternal _TransitionToObserverRequestProto_default_instance_;
PROTOBUF_CONSTEXPR TransitionToObserverResponseProto::TransitionToObserverResponseProto(
    ::_pbi::ConstantInitialized) {}
struct TransitionToObserverResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransitionToObserverResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransitionToObserverResponseProtoDefaultTypeInternal() {}
  union {
    TransitionToObserverResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransitionToObserverResponseProtoDefaultTypeInternal _TransitionToObserverResponseProto_default_instance_;
PROTOBUF_CONSTEXPR GetServiceStatusRequestProto::GetServiceStatusRequestProto(
    ::_pbi::ConstantInitialized) {}
struct GetServiceStatusRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServiceStatusRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServiceStatusRequestProtoDefaultTypeInternal() {}
  union {
    GetServiceStatusRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServiceStatusRequestProtoDefaultTypeInternal _GetServiceStatusRequestProto_default_instance_;
PROTOBUF_CONSTEXPR GetServiceStatusResponseProto::GetServiceStatusResponseProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.notreadyreason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_.readytobecomeactive_)*/false} {}
struct GetServiceStatusResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetServiceStatusResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetServiceStatusResponseProtoDefaultTypeInternal() {}
  union {
    GetServiceStatusResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetServiceStatusResponseProtoDefaultTypeInternal _GetServiceStatusResponseProto_default_instance_;
}  // namespace common
}  // namespace hadoop
static ::_pb::Metadata file_level_metadata_HAServiceProtocol_2eproto[11];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_HAServiceProtocol_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HAServiceProtocol_2eproto = nullptr;

const uint32_t TableStruct_HAServiceProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hadoop::common::HAStateChangeRequestInfoProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::HAStateChangeRequestInfoProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::HAStateChangeRequestInfoProto, _impl_.reqsource_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::MonitorHealthRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::MonitorHealthResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToActiveRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToActiveRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToActiveRequestProto, _impl_.reqinfo_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToActiveResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToStandbyRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToStandbyRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToStandbyRequestProto, _impl_.reqinfo_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToStandbyResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToObserverRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToObserverRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToObserverRequestProto, _impl_.reqinfo_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TransitionToObserverResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusResponseProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusResponseProto, _impl_.state_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusResponseProto, _impl_.readytobecomeactive_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetServiceStatusResponseProto, _impl_.notreadyreason_),
  1,
  2,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::hadoop::common::HAStateChangeRequestInfoProto)},
  { 8, -1, -1, sizeof(::hadoop::common::MonitorHealthRequestProto)},
  { 14, -1, -1, sizeof(::hadoop::common::MonitorHealthResponseProto)},
  { 20, 27, -1, sizeof(::hadoop::common::TransitionToActiveRequestProto)},
  { 28, -1, -1, sizeof(::hadoop::common::TransitionToActiveResponseProto)},
  { 34, 41, -1, sizeof(::hadoop::common::TransitionToStandbyRequestProto)},
  { 42, -1, -1, sizeof(::hadoop::common::TransitionToStandbyResponseProto)},
  { 48, 55, -1, sizeof(::hadoop::common::TransitionToObserverRequestProto)},
  { 56, -1, -1, sizeof(::hadoop::common::TransitionToObserverResponseProto)},
  { 62, -1, -1, sizeof(::hadoop::common::GetServiceStatusRequestProto)},
  { 68, 77, -1, sizeof(::hadoop::common::GetServiceStatusResponseProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hadoop::common::_HAStateChangeRequestInfoProto_default_instance_._instance,
  &::hadoop::common::_MonitorHealthRequestProto_default_instance_._instance,
  &::hadoop::common::_MonitorHealthResponseProto_default_instance_._instance,
  &::hadoop::common::_TransitionToActiveRequestProto_default_instance_._instance,
  &::hadoop::common::_TransitionToActiveResponseProto_default_instance_._instance,
  &::hadoop::common::_TransitionToStandbyRequestProto_default_instance_._instance,
  &::hadoop::common::_TransitionToStandbyResponseProto_default_instance_._instance,
  &::hadoop::common::_TransitionToObserverRequestProto_default_instance_._instance,
  &::hadoop::common::_TransitionToObserverResponseProto_default_instance_._instance,
  &::hadoop::common::_GetServiceStatusRequestProto_default_instance_._instance,
  &::hadoop::common::_GetServiceStatusResponseProto_default_instance_._instance,
};

const char descriptor_table_protodef_HAServiceProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027HAServiceProtocol.proto\022\rhadoop.common"
  "\"R\n\035HAStateChangeRequestInfoProto\0221\n\treq"
  "Source\030\001 \002(\0162\036.hadoop.common.HARequestSo"
  "urce\"\033\n\031MonitorHealthRequestProto\"\034\n\032Mon"
  "itorHealthResponseProto\"_\n\036TransitionToA"
  "ctiveRequestProto\022=\n\007reqInfo\030\001 \002(\0132,.had"
  "oop.common.HAStateChangeRequestInfoProto"
  "\"!\n\037TransitionToActiveResponseProto\"`\n\037T"
  "ransitionToStandbyRequestProto\022=\n\007reqInf"
  "o\030\001 \002(\0132,.hadoop.common.HAStateChangeReq"
  "uestInfoProto\"\"\n TransitionToStandbyResp"
  "onseProto\"a\n TransitionToObserverRequest"
  "Proto\022=\n\007reqInfo\030\001 \002(\0132,.hadoop.common.H"
  "AStateChangeRequestInfoProto\"#\n!Transiti"
  "onToObserverResponseProto\"\036\n\034GetServiceS"
  "tatusRequestProto\"\207\001\n\035GetServiceStatusRe"
  "sponseProto\0221\n\005state\030\001 \002(\0162\".hadoop.comm"
  "on.HAServiceStateProto\022\033\n\023readyToBecomeA"
  "ctive\030\002 \001(\010\022\026\n\016notReadyReason\030\003 \001(\t*N\n\023H"
  "AServiceStateProto\022\020\n\014INITIALIZING\020\000\022\n\n\006"
  "ACTIVE\020\001\022\013\n\007STANDBY\020\002\022\014\n\010OBSERVER\020\003*W\n\017H"
  "ARequestSource\022\023\n\017REQUEST_BY_USER\020\000\022\032\n\026R"
  "EQUEST_BY_USER_FORCED\020\001\022\023\n\017REQUEST_BY_ZK"
  "FC\020\0022\327\004\n\030HAServiceProtocolService\022d\n\rmon"
  "itorHealth\022(.hadoop.common.MonitorHealth"
  "RequestProto\032).hadoop.common.MonitorHeal"
  "thResponseProto\022s\n\022transitionToActive\022-."
  "hadoop.common.TransitionToActiveRequestP"
  "roto\032..hadoop.common.TransitionToActiveR"
  "esponseProto\022v\n\023transitionToStandby\022..ha"
  "doop.common.TransitionToStandbyRequestPr"
  "oto\032/.hadoop.common.TransitionToStandbyR"
  "esponseProto\022y\n\024transitionToObserver\022/.h"
  "adoop.common.TransitionToObserverRequest"
  "Proto\0320.hadoop.common.TransitionToObserv"
  "erResponseProto\022m\n\020getServiceStatus\022+.ha"
  "doop.common.GetServiceStatusRequestProto"
  "\032,.hadoop.common.GetServiceStatusRespons"
  "eProtoB;\n\032org.apache.hadoop.ha.protoB\027HA"
  "ServiceProtocolProtos\210\001\001\240\001\001"
  ;
static ::_pbi::once_flag descriptor_table_HAServiceProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HAServiceProtocol_2eproto = {
    false, false, 1587, descriptor_table_protodef_HAServiceProtocol_2eproto,
    "HAServiceProtocol.proto",
    &descriptor_table_HAServiceProtocol_2eproto_once, nullptr, 0, 11,
    schemas, file_default_instances, TableStruct_HAServiceProtocol_2eproto::offsets,
    file_level_metadata_HAServiceProtocol_2eproto, file_level_enum_descriptors_HAServiceProtocol_2eproto,
    file_level_service_descriptors_HAServiceProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HAServiceProtocol_2eproto_getter() {
  return &descriptor_table_HAServiceProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HAServiceProtocol_2eproto(&descriptor_table_HAServiceProtocol_2eproto);
namespace hadoop {
namespace common {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HAServiceStateProto_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_HAServiceProtocol_2eproto);
  return file_level_enum_descriptors_HAServiceProtocol_2eproto[0];
}
bool HAServiceStateProto_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HARequestSource_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_HAServiceProtocol_2eproto);
  return file_level_enum_descriptors_HAServiceProtocol_2eproto[1];
}
bool HARequestSource_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class HAStateChangeRequestInfoProto::_Internal {
 public:
  using HasBits = decltype(std::declval<HAStateChangeRequestInfoProto>()._impl_._has_bits_);
  static void set_has_reqsource(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

HAStateChangeRequestInfoProto::HAStateChangeRequestInfoProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.HAStateChangeRequestInfoProto)
}
HAStateChangeRequestInfoProto::HAStateChangeRequestInfoProto(const HAStateChangeRequestInfoProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HAStateChangeRequestInfoProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqsource_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.reqsource_ = from._impl_.reqsource_;
  // @@protoc_insertion_point(copy_constructor:hadoop.common.HAStateChangeRequestInfoProto)
}

inline void HAStateChangeRequestInfoProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqsource_){0}
  };
}

HAStateChangeRequestInfoProto::~HAStateChangeRequestInfoProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.HAStateChangeRequestInfoProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HAStateChangeRequestInfoProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HAStateChangeRequestInfoProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HAStateChangeRequestInfoProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.HAStateChangeRequestInfoProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqsource_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HAStateChangeRequestInfoProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.HARequestSource reqSource = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::hadoop::common::HARequestSource_IsValid(val))) {
            _internal_set_reqsource(static_cast<::hadoop::common::HARequestSource>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HAStateChangeRequestInfoProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.HAStateChangeRequestInfoProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.HARequestSource reqSource = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_reqsource(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.HAStateChangeRequestInfoProto)
  return target;
}

size_t HAStateChangeRequestInfoProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.HAStateChangeRequestInfoProto)
  size_t total_size = 0;

  // required .hadoop.common.HARequestSource reqSource = 1;
  if (_internal_has_reqsource()) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_reqsource());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HAStateChangeRequestInfoProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HAStateChangeRequestInfoProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HAStateChangeRequestInfoProto::GetClassData() const { return &_class_data_; }


void HAStateChangeRequestInfoProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HAStateChangeRequestInfoProto*>(&to_msg);
  auto& from = static_cast<const HAStateChangeRequestInfoProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.HAStateChangeRequestInfoProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_reqsource()) {
    _this->_internal_set_reqsource(from._internal_reqsource());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HAStateChangeRequestInfoProto::CopyFrom(const HAStateChangeRequestInfoProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.HAStateChangeRequestInfoProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HAStateChangeRequestInfoProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void HAStateChangeRequestInfoProto::InternalSwap(HAStateChangeRequestInfoProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.reqsource_, other->_impl_.reqsource_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HAStateChangeRequestInfoProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[0]);
}

// ===================================================================

class MonitorHealthRequestProto::_Internal {
 public:
};

MonitorHealthRequestProto::MonitorHealthRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.MonitorHealthRequestProto)
}
MonitorHealthRequestProto::MonitorHealthRequestProto(const MonitorHealthRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MonitorHealthRequestProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.MonitorHealthRequestProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MonitorHealthRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MonitorHealthRequestProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MonitorHealthRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[1]);
}

// ===================================================================

class MonitorHealthResponseProto::_Internal {
 public:
};

MonitorHealthResponseProto::MonitorHealthResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.MonitorHealthResponseProto)
}
MonitorHealthResponseProto::MonitorHealthResponseProto(const MonitorHealthResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  MonitorHealthResponseProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.MonitorHealthResponseProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MonitorHealthResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MonitorHealthResponseProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MonitorHealthResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[2]);
}

// ===================================================================

class TransitionToActiveRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<TransitionToActiveRequestProto>()._impl_._has_bits_);
  static const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo(const TransitionToActiveRequestProto* msg);
  static void set_has_reqinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::HAStateChangeRequestInfoProto&
TransitionToActiveRequestProto::_Internal::reqinfo(const TransitionToActiveRequestProto* msg) {
  return *msg->_impl_.reqinfo_;
}
TransitionToActiveRequestProto::TransitionToActiveRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToActiveRequestProto)
}
TransitionToActiveRequestProto::TransitionToActiveRequestProto(const TransitionToActiveRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransitionToActiveRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_reqinfo()) {
    _this->_impl_.reqinfo_ = new ::hadoop::common::HAStateChangeRequestInfoProto(*from._impl_.reqinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToActiveRequestProto)
}

inline void TransitionToActiveRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}
  };
}

TransitionToActiveRequestProto::~TransitionToActiveRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.TransitionToActiveRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransitionToActiveRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.reqinfo_;
}

void TransitionToActiveRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransitionToActiveRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.TransitionToActiveRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.reqinfo_ != nullptr);
    _impl_.reqinfo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransitionToActiveRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_reqinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransitionToActiveRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.TransitionToActiveRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::reqinfo(this),
        _Internal::reqinfo(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.TransitionToActiveRequestProto)
  return target;
}

size_t TransitionToActiveRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.TransitionToActiveRequestProto)
  size_t total_size = 0;

  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (_internal_has_reqinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.reqinfo_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToActiveRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransitionToActiveRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToActiveRequestProto::GetClassData() const { return &_class_data_; }


void TransitionToActiveRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransitionToActiveRequestProto*>(&to_msg);
  auto& from = static_cast<const TransitionToActiveRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.TransitionToActiveRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_reqinfo()) {
    _this->_internal_mutable_reqinfo()->::hadoop::common::HAStateChangeRequestInfoProto::MergeFrom(
        from._internal_reqinfo());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransitionToActiveRequestProto::CopyFrom(const TransitionToActiveRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.TransitionToActiveRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransitionToActiveRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_reqinfo()) {
    if (!_impl_.reqinfo_->IsInitialized()) return false;
  }
  return true;
}

void TransitionToActiveRequestProto::InternalSwap(TransitionToActiveRequestProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.reqinfo_, other->_impl_.reqinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransitionToActiveRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[3]);
}

// ===================================================================

class TransitionToActiveResponseProto::_Internal {
 public:
};

TransitionToActiveResponseProto::TransitionToActiveResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToActiveResponseProto)
}
TransitionToActiveResponseProto::TransitionToActiveResponseProto(const TransitionToActiveResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  TransitionToActiveResponseProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToActiveResponseProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToActiveResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToActiveResponseProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata TransitionToActiveResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[4]);
}

// ===================================================================

class TransitionToStandbyRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<TransitionToStandbyRequestProto>()._impl_._has_bits_);
  static const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo(const TransitionToStandbyRequestProto* msg);
  static void set_has_reqinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::HAStateChangeRequestInfoProto&
TransitionToStandbyRequestProto::_Internal::reqinfo(const TransitionToStandbyRequestProto* msg) {
  return *msg->_impl_.reqinfo_;
}
TransitionToStandbyRequestProto::TransitionToStandbyRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToStandbyRequestProto)
}
TransitionToStandbyRequestProto::TransitionToStandbyRequestProto(const TransitionToStandbyRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransitionToStandbyRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_reqinfo()) {
    _this->_impl_.reqinfo_ = new ::hadoop::common::HAStateChangeRequestInfoProto(*from._impl_.reqinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToStandbyRequestProto)
}

inline void TransitionToStandbyRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}
  };
}

TransitionToStandbyRequestProto::~TransitionToStandbyRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.TransitionToStandbyRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransitionToStandbyRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.reqinfo_;
}

void TransitionToStandbyRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransitionToStandbyRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.TransitionToStandbyRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.reqinfo_ != nullptr);
    _impl_.reqinfo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransitionToStandbyRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_reqinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransitionToStandbyRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.TransitionToStandbyRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::reqinfo(this),
        _Internal::reqinfo(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.TransitionToStandbyRequestProto)
  return target;
}

size_t TransitionToStandbyRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.TransitionToStandbyRequestProto)
  size_t total_size = 0;

  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (_internal_has_reqinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.reqinfo_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToStandbyRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransitionToStandbyRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToStandbyRequestProto::GetClassData() const { return &_class_data_; }


void TransitionToStandbyRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransitionToStandbyRequestProto*>(&to_msg);
  auto& from = static_cast<const TransitionToStandbyRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.TransitionToStandbyRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_reqinfo()) {
    _this->_internal_mutable_reqinfo()->::hadoop::common::HAStateChangeRequestInfoProto::MergeFrom(
        from._internal_reqinfo());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransitionToStandbyRequestProto::CopyFrom(const TransitionToStandbyRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.TransitionToStandbyRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransitionToStandbyRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_reqinfo()) {
    if (!_impl_.reqinfo_->IsInitialized()) return false;
  }
  return true;
}

void TransitionToStandbyRequestProto::InternalSwap(TransitionToStandbyRequestProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.reqinfo_, other->_impl_.reqinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransitionToStandbyRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[5]);
}

// ===================================================================

class TransitionToStandbyResponseProto::_Internal {
 public:
};

TransitionToStandbyResponseProto::TransitionToStandbyResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToStandbyResponseProto)
}
TransitionToStandbyResponseProto::TransitionToStandbyResponseProto(const TransitionToStandbyResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  TransitionToStandbyResponseProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToStandbyResponseProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToStandbyResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToStandbyResponseProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata TransitionToStandbyResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[6]);
}

// ===================================================================

class TransitionToObserverRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<TransitionToObserverRequestProto>()._impl_._has_bits_);
  static const ::hadoop::common::HAStateChangeRequestInfoProto& reqinfo(const TransitionToObserverRequestProto* msg);
  static void set_has_reqinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::HAStateChangeRequestInfoProto&
TransitionToObserverRequestProto::_Internal::reqinfo(const TransitionToObserverRequestProto* msg) {
  return *msg->_impl_.reqinfo_;
}
TransitionToObserverRequestProto::TransitionToObserverRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToObserverRequestProto)
}
TransitionToObserverRequestProto::TransitionToObserverRequestProto(const TransitionToObserverRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransitionToObserverRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_reqinfo()) {
    _this->_impl_.reqinfo_ = new ::hadoop::common::HAStateChangeRequestInfoProto(*from._impl_.reqinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToObserverRequestProto)
}

inline void TransitionToObserverRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reqinfo_){nullptr}
  };
}

TransitionToObserverRequestProto::~TransitionToObserverRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.TransitionToObserverRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransitionToObserverRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.reqinfo_;
}

void TransitionToObserverRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransitionToObserverRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.TransitionToObserverRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.reqinfo_ != nullptr);
    _impl_.reqinfo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransitionToObserverRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_reqinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransitionToObserverRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.TransitionToObserverRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::reqinfo(this),
        _Internal::reqinfo(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.TransitionToObserverRequestProto)
  return target;
}

size_t TransitionToObserverRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.TransitionToObserverRequestProto)
  size_t total_size = 0;

  // required .hadoop.common.HAStateChangeRequestInfoProto reqInfo = 1;
  if (_internal_has_reqinfo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.reqinfo_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToObserverRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransitionToObserverRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToObserverRequestProto::GetClassData() const { return &_class_data_; }


void TransitionToObserverRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransitionToObserverRequestProto*>(&to_msg);
  auto& from = static_cast<const TransitionToObserverRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.TransitionToObserverRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_reqinfo()) {
    _this->_internal_mutable_reqinfo()->::hadoop::common::HAStateChangeRequestInfoProto::MergeFrom(
        from._internal_reqinfo());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransitionToObserverRequestProto::CopyFrom(const TransitionToObserverRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.TransitionToObserverRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransitionToObserverRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_reqinfo()) {
    if (!_impl_.reqinfo_->IsInitialized()) return false;
  }
  return true;
}

void TransitionToObserverRequestProto::InternalSwap(TransitionToObserverRequestProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.reqinfo_, other->_impl_.reqinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransitionToObserverRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[7]);
}

// ===================================================================

class TransitionToObserverResponseProto::_Internal {
 public:
};

TransitionToObserverResponseProto::TransitionToObserverResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TransitionToObserverResponseProto)
}
TransitionToObserverResponseProto::TransitionToObserverResponseProto(const TransitionToObserverResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  TransitionToObserverResponseProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TransitionToObserverResponseProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransitionToObserverResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransitionToObserverResponseProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata TransitionToObserverResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[8]);
}

// ===================================================================

class GetServiceStatusRequestProto::_Internal {
 public:
};

GetServiceStatusRequestProto::GetServiceStatusRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.GetServiceStatusRequestProto)
}
GetServiceStatusRequestProto::GetServiceStatusRequestProto(const GetServiceStatusRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  GetServiceStatusRequestProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.GetServiceStatusRequestProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetServiceStatusRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetServiceStatusRequestProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GetServiceStatusRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[9]);
}

// ===================================================================

class GetServiceStatusResponseProto::_Internal {
 public:
  using HasBits = decltype(std::declval<GetServiceStatusResponseProto>()._impl_._has_bits_);
  static void set_has_state(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_readytobecomeactive(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_notreadyreason(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

GetServiceStatusResponseProto::GetServiceStatusResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.GetServiceStatusResponseProto)
}
GetServiceStatusResponseProto::GetServiceStatusResponseProto(const GetServiceStatusResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetServiceStatusResponseProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.notreadyreason_){}
    , decltype(_impl_.state_){}
    , decltype(_impl_.readytobecomeactive_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.notreadyreason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.notreadyreason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_notreadyreason()) {
    _this->_impl_.notreadyreason_.Set(from._internal_notreadyreason(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.state_, &from._impl_.state_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.readytobecomeactive_) -
    reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.readytobecomeactive_));
  // @@protoc_insertion_point(copy_constructor:hadoop.common.GetServiceStatusResponseProto)
}

inline void GetServiceStatusResponseProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.notreadyreason_){}
    , decltype(_impl_.state_){0}
    , decltype(_impl_.readytobecomeactive_){false}
  };
  _impl_.notreadyreason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.notreadyreason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetServiceStatusResponseProto::~GetServiceStatusResponseProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.GetServiceStatusResponseProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetServiceStatusResponseProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.notreadyreason_.Destroy();
}

void GetServiceStatusResponseProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetServiceStatusResponseProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.GetServiceStatusResponseProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.notreadyreason_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.state_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.readytobecomeactive_) -
        reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.readytobecomeactive_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetServiceStatusResponseProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.HAServiceStateProto state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::hadoop::common::HAServiceStateProto_IsValid(val))) {
            _internal_set_state(static_cast<::hadoop::common::HAServiceStateProto>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional bool readyToBecomeActive = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_readytobecomeactive(&has_bits);
          _impl_.readytobecomeactive_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string notReadyReason = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_notreadyreason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.GetServiceStatusResponseProto.notReadyReason");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetServiceStatusResponseProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.GetServiceStatusResponseProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.HAServiceStateProto state = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_state(), target);
  }

  // optional bool readyToBecomeActive = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_readytobecomeactive(), target);
  }

  // optional string notReadyReason = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_notreadyreason().data(), static_cast<int>(this->_internal_notreadyreason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.GetServiceStatusResponseProto.notReadyReason");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_notreadyreason(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.GetServiceStatusResponseProto)
  return target;
}

size_t GetServiceStatusResponseProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.GetServiceStatusResponseProto)
  size_t total_size = 0;

  // required .hadoop.common.HAServiceStateProto state = 1;
  if (_internal_has_state()) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_state());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string notReadyReason = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_notreadyreason());
  }

  // optional bool readyToBecomeActive = 2;
  if (cached_has_bits & 0x00000004u) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetServiceStatusResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetServiceStatusResponseProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetServiceStatusResponseProto::GetClassData() const { return &_class_data_; }


void GetServiceStatusResponseProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetServiceStatusResponseProto*>(&to_msg);
  auto& from = static_cast<const GetServiceStatusResponseProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.GetServiceStatusResponseProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_notreadyreason(from._internal_notreadyreason());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.state_ = from._impl_.state_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.readytobecomeactive_ = from._impl_.readytobecomeactive_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetServiceStatusResponseProto::CopyFrom(const GetServiceStatusResponseProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.GetServiceStatusResponseProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetServiceStatusResponseProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void GetServiceStatusResponseProto::InternalSwap(GetServiceStatusResponseProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.notreadyreason_, lhs_arena,
      &other->_impl_.notreadyreason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetServiceStatusResponseProto, _impl_.readytobecomeactive_)
      + sizeof(GetServiceStatusResponseProto::_impl_.readytobecomeactive_)
      - PROTOBUF_FIELD_OFFSET(GetServiceStatusResponseProto, _impl_.state_)>(
          reinterpret_cast<char*>(&_impl_.state_),
          reinterpret_cast<char*>(&other->_impl_.state_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetServiceStatusResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HAServiceProtocol_2eproto_getter, &descriptor_table_HAServiceProtocol_2eproto_once,
      file_level_metadata_HAServiceProtocol_2eproto[10]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hadoop::common::HAStateChangeRequestInfoProto*
Arena::CreateMaybeMessage< ::hadoop::common::HAStateChangeRequestInfoProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::HAStateChangeRequestInfoProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::MonitorHealthRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::MonitorHealthRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::MonitorHealthRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::MonitorHealthResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::MonitorHealthResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::MonitorHealthResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToActiveRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToActiveRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToActiveRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToActiveResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToActiveResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToActiveResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToStandbyRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToStandbyRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToStandbyRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToStandbyResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToStandbyResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToStandbyResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToObserverRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToObserverRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToObserverRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::TransitionToObserverResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::TransitionToObserverResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TransitionToObserverResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::GetServiceStatusRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::GetServiceStatusRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::GetServiceStatusRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::GetServiceStatusResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::GetServiceStatusResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::GetServiceStatusResponseProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
