// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcConnectionContext.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IpcConnectionContext_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IpcConnectionContext_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IpcConnectionContext_2eproto;
namespace hadoop {
namespace common {
class IpcConnectionContextProto;
class IpcConnectionContextProtoDefaultTypeInternal;
extern IpcConnectionContextProtoDefaultTypeInternal _IpcConnectionContextProto_default_instance_;
class UserInformationProto;
class UserInformationProtoDefaultTypeInternal;
extern UserInformationProtoDefaultTypeInternal _UserInformationProto_default_instance_;
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> ::hadoop::common::IpcConnectionContextProto* Arena::CreateMaybeMessage<::hadoop::common::IpcConnectionContextProto>(Arena*);
template<> ::hadoop::common::UserInformationProto* Arena::CreateMaybeMessage<::hadoop::common::UserInformationProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hadoop {
namespace common {

// ===================================================================

class UserInformationProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.UserInformationProto) */ {
 public:
  inline UserInformationProto() : UserInformationProto(nullptr) {};
  virtual ~UserInformationProto();

  UserInformationProto(const UserInformationProto& from);
  UserInformationProto(UserInformationProto&& from) noexcept
    : UserInformationProto() {
    *this = ::std::move(from);
  }

  inline UserInformationProto& operator=(const UserInformationProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInformationProto& operator=(UserInformationProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UserInformationProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserInformationProto* internal_default_instance() {
    return reinterpret_cast<const UserInformationProto*>(
               &_UserInformationProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserInformationProto& a, UserInformationProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInformationProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserInformationProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UserInformationProto* New() const final {
    return CreateMaybeMessage<UserInformationProto>(nullptr);
  }

  UserInformationProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UserInformationProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UserInformationProto& from);
  void MergeFrom(const UserInformationProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInformationProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.UserInformationProto";
  }
  protected:
  explicit UserInformationProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IpcConnectionContext_2eproto);
    return ::descriptor_table_IpcConnectionContext_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEffectiveUserFieldNumber = 1,
    kRealUserFieldNumber = 2,
  };
  // optional string effectiveUser = 1;
  bool has_effectiveuser() const;
  private:
  bool _internal_has_effectiveuser() const;
  public:
  void clear_effectiveuser();
  const std::string& effectiveuser() const;
  void set_effectiveuser(const std::string& value);
  void set_effectiveuser(std::string&& value);
  void set_effectiveuser(const char* value);
  void set_effectiveuser(const char* value, size_t size);
  std::string* mutable_effectiveuser();
  std::string* release_effectiveuser();
  void set_allocated_effectiveuser(std::string* effectiveuser);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_effectiveuser();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_effectiveuser(
      std::string* effectiveuser);
  private:
  const std::string& _internal_effectiveuser() const;
  void _internal_set_effectiveuser(const std::string& value);
  std::string* _internal_mutable_effectiveuser();
  public:

  // optional string realUser = 2;
  bool has_realuser() const;
  private:
  bool _internal_has_realuser() const;
  public:
  void clear_realuser();
  const std::string& realuser() const;
  void set_realuser(const std::string& value);
  void set_realuser(std::string&& value);
  void set_realuser(const char* value);
  void set_realuser(const char* value, size_t size);
  std::string* mutable_realuser();
  std::string* release_realuser();
  void set_allocated_realuser(std::string* realuser);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_realuser();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_realuser(
      std::string* realuser);
  private:
  const std::string& _internal_realuser() const;
  void _internal_set_realuser(const std::string& value);
  std::string* _internal_mutable_realuser();
  public:

  // @@protoc_insertion_point(class_scope:hadoop.common.UserInformationProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr effectiveuser_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr realuser_;
  friend struct ::TableStruct_IpcConnectionContext_2eproto;
};
// -------------------------------------------------------------------

class IpcConnectionContextProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.IpcConnectionContextProto) */ {
 public:
  inline IpcConnectionContextProto() : IpcConnectionContextProto(nullptr) {};
  virtual ~IpcConnectionContextProto();

  IpcConnectionContextProto(const IpcConnectionContextProto& from);
  IpcConnectionContextProto(IpcConnectionContextProto&& from) noexcept
    : IpcConnectionContextProto() {
    *this = ::std::move(from);
  }

  inline IpcConnectionContextProto& operator=(const IpcConnectionContextProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline IpcConnectionContextProto& operator=(IpcConnectionContextProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IpcConnectionContextProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IpcConnectionContextProto* internal_default_instance() {
    return reinterpret_cast<const IpcConnectionContextProto*>(
               &_IpcConnectionContextProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IpcConnectionContextProto& a, IpcConnectionContextProto& b) {
    a.Swap(&b);
  }
  inline void Swap(IpcConnectionContextProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IpcConnectionContextProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IpcConnectionContextProto* New() const final {
    return CreateMaybeMessage<IpcConnectionContextProto>(nullptr);
  }

  IpcConnectionContextProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IpcConnectionContextProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IpcConnectionContextProto& from);
  void MergeFrom(const IpcConnectionContextProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IpcConnectionContextProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.IpcConnectionContextProto";
  }
  protected:
  explicit IpcConnectionContextProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IpcConnectionContext_2eproto);
    return ::descriptor_table_IpcConnectionContext_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProtocolFieldNumber = 3,
    kUserInfoFieldNumber = 2,
  };
  // optional string protocol = 3;
  bool has_protocol() const;
  private:
  bool _internal_has_protocol() const;
  public:
  void clear_protocol();
  const std::string& protocol() const;
  void set_protocol(const std::string& value);
  void set_protocol(std::string&& value);
  void set_protocol(const char* value);
  void set_protocol(const char* value, size_t size);
  std::string* mutable_protocol();
  std::string* release_protocol();
  void set_allocated_protocol(std::string* protocol);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_protocol();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_protocol(
      std::string* protocol);
  private:
  const std::string& _internal_protocol() const;
  void _internal_set_protocol(const std::string& value);
  std::string* _internal_mutable_protocol();
  public:

  // optional .hadoop.common.UserInformationProto userInfo = 2;
  bool has_userinfo() const;
  private:
  bool _internal_has_userinfo() const;
  public:
  void clear_userinfo();
  const ::hadoop::common::UserInformationProto& userinfo() const;
  ::hadoop::common::UserInformationProto* release_userinfo();
  ::hadoop::common::UserInformationProto* mutable_userinfo();
  void set_allocated_userinfo(::hadoop::common::UserInformationProto* userinfo);
  private:
  const ::hadoop::common::UserInformationProto& _internal_userinfo() const;
  ::hadoop::common::UserInformationProto* _internal_mutable_userinfo();
  public:
  void unsafe_arena_set_allocated_userinfo(
      ::hadoop::common::UserInformationProto* userinfo);
  ::hadoop::common::UserInformationProto* unsafe_arena_release_userinfo();

  // @@protoc_insertion_point(class_scope:hadoop.common.IpcConnectionContextProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protocol_;
  ::hadoop::common::UserInformationProto* userinfo_;
  friend struct ::TableStruct_IpcConnectionContext_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInformationProto

// optional string effectiveUser = 1;
inline bool UserInformationProto::_internal_has_effectiveuser() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UserInformationProto::has_effectiveuser() const {
  return _internal_has_effectiveuser();
}
inline void UserInformationProto::clear_effectiveuser() {
  effectiveuser_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UserInformationProto::effectiveuser() const {
  // @@protoc_insertion_point(field_get:hadoop.common.UserInformationProto.effectiveUser)
  return _internal_effectiveuser();
}
inline void UserInformationProto::set_effectiveuser(const std::string& value) {
  _internal_set_effectiveuser(value);
  // @@protoc_insertion_point(field_set:hadoop.common.UserInformationProto.effectiveUser)
}
inline std::string* UserInformationProto::mutable_effectiveuser() {
  // @@protoc_insertion_point(field_mutable:hadoop.common.UserInformationProto.effectiveUser)
  return _internal_mutable_effectiveuser();
}
inline const std::string& UserInformationProto::_internal_effectiveuser() const {
  return effectiveuser_.Get();
}
inline void UserInformationProto::_internal_set_effectiveuser(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  effectiveuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UserInformationProto::set_effectiveuser(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  effectiveuser_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hadoop.common.UserInformationProto.effectiveUser)
}
inline void UserInformationProto::set_effectiveuser(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  effectiveuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hadoop.common.UserInformationProto.effectiveUser)
}
inline void UserInformationProto::set_effectiveuser(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  effectiveuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hadoop.common.UserInformationProto.effectiveUser)
}
inline std::string* UserInformationProto::_internal_mutable_effectiveuser() {
  _has_bits_[0] |= 0x00000001u;
  return effectiveuser_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UserInformationProto::release_effectiveuser() {
  // @@protoc_insertion_point(field_release:hadoop.common.UserInformationProto.effectiveUser)
  if (!_internal_has_effectiveuser()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return effectiveuser_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserInformationProto::set_allocated_effectiveuser(std::string* effectiveuser) {
  if (effectiveuser != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  effectiveuser_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), effectiveuser,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.UserInformationProto.effectiveUser)
}
inline std::string* UserInformationProto::unsafe_arena_release_effectiveuser() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hadoop.common.UserInformationProto.effectiveUser)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return effectiveuser_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void UserInformationProto::unsafe_arena_set_allocated_effectiveuser(
    std::string* effectiveuser) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (effectiveuser != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  effectiveuser_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      effectiveuser, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.UserInformationProto.effectiveUser)
}

// optional string realUser = 2;
inline bool UserInformationProto::_internal_has_realuser() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UserInformationProto::has_realuser() const {
  return _internal_has_realuser();
}
inline void UserInformationProto::clear_realuser() {
  realuser_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& UserInformationProto::realuser() const {
  // @@protoc_insertion_point(field_get:hadoop.common.UserInformationProto.realUser)
  return _internal_realuser();
}
inline void UserInformationProto::set_realuser(const std::string& value) {
  _internal_set_realuser(value);
  // @@protoc_insertion_point(field_set:hadoop.common.UserInformationProto.realUser)
}
inline std::string* UserInformationProto::mutable_realuser() {
  // @@protoc_insertion_point(field_mutable:hadoop.common.UserInformationProto.realUser)
  return _internal_mutable_realuser();
}
inline const std::string& UserInformationProto::_internal_realuser() const {
  return realuser_.Get();
}
inline void UserInformationProto::_internal_set_realuser(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  realuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UserInformationProto::set_realuser(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  realuser_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hadoop.common.UserInformationProto.realUser)
}
inline void UserInformationProto::set_realuser(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  realuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hadoop.common.UserInformationProto.realUser)
}
inline void UserInformationProto::set_realuser(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  realuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hadoop.common.UserInformationProto.realUser)
}
inline std::string* UserInformationProto::_internal_mutable_realuser() {
  _has_bits_[0] |= 0x00000002u;
  return realuser_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UserInformationProto::release_realuser() {
  // @@protoc_insertion_point(field_release:hadoop.common.UserInformationProto.realUser)
  if (!_internal_has_realuser()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return realuser_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserInformationProto::set_allocated_realuser(std::string* realuser) {
  if (realuser != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  realuser_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), realuser,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.UserInformationProto.realUser)
}
inline std::string* UserInformationProto::unsafe_arena_release_realuser() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hadoop.common.UserInformationProto.realUser)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return realuser_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void UserInformationProto::unsafe_arena_set_allocated_realuser(
    std::string* realuser) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (realuser != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  realuser_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      realuser, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.UserInformationProto.realUser)
}

// -------------------------------------------------------------------

// IpcConnectionContextProto

// optional .hadoop.common.UserInformationProto userInfo = 2;
inline bool IpcConnectionContextProto::_internal_has_userinfo() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || userinfo_ != nullptr);
  return value;
}
inline bool IpcConnectionContextProto::has_userinfo() const {
  return _internal_has_userinfo();
}
inline void IpcConnectionContextProto::clear_userinfo() {
  if (userinfo_ != nullptr) userinfo_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::hadoop::common::UserInformationProto& IpcConnectionContextProto::_internal_userinfo() const {
  const ::hadoop::common::UserInformationProto* p = userinfo_;
  return p != nullptr ? *p : *reinterpret_cast<const ::hadoop::common::UserInformationProto*>(
      &::hadoop::common::_UserInformationProto_default_instance_);
}
inline const ::hadoop::common::UserInformationProto& IpcConnectionContextProto::userinfo() const {
  // @@protoc_insertion_point(field_get:hadoop.common.IpcConnectionContextProto.userInfo)
  return _internal_userinfo();
}
inline void IpcConnectionContextProto::unsafe_arena_set_allocated_userinfo(
    ::hadoop::common::UserInformationProto* userinfo) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(userinfo_);
  }
  userinfo_ = userinfo;
  if (userinfo) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.IpcConnectionContextProto.userInfo)
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::release_userinfo() {
  auto temp = unsafe_arena_release_userinfo();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::unsafe_arena_release_userinfo() {
  // @@protoc_insertion_point(field_release:hadoop.common.IpcConnectionContextProto.userInfo)
  _has_bits_[0] &= ~0x00000002u;
  ::hadoop::common::UserInformationProto* temp = userinfo_;
  userinfo_ = nullptr;
  return temp;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::_internal_mutable_userinfo() {
  _has_bits_[0] |= 0x00000002u;
  if (userinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::hadoop::common::UserInformationProto>(GetArena());
    userinfo_ = p;
  }
  return userinfo_;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::mutable_userinfo() {
  // @@protoc_insertion_point(field_mutable:hadoop.common.IpcConnectionContextProto.userInfo)
  return _internal_mutable_userinfo();
}
inline void IpcConnectionContextProto::set_allocated_userinfo(::hadoop::common::UserInformationProto* userinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete userinfo_;
  }
  if (userinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(userinfo);
    if (message_arena != submessage_arena) {
      userinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, userinfo, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  userinfo_ = userinfo;
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.IpcConnectionContextProto.userInfo)
}

// optional string protocol = 3;
inline bool IpcConnectionContextProto::_internal_has_protocol() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IpcConnectionContextProto::has_protocol() const {
  return _internal_has_protocol();
}
inline void IpcConnectionContextProto::clear_protocol() {
  protocol_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& IpcConnectionContextProto::protocol() const {
  // @@protoc_insertion_point(field_get:hadoop.common.IpcConnectionContextProto.protocol)
  return _internal_protocol();
}
inline void IpcConnectionContextProto::set_protocol(const std::string& value) {
  _internal_set_protocol(value);
  // @@protoc_insertion_point(field_set:hadoop.common.IpcConnectionContextProto.protocol)
}
inline std::string* IpcConnectionContextProto::mutable_protocol() {
  // @@protoc_insertion_point(field_mutable:hadoop.common.IpcConnectionContextProto.protocol)
  return _internal_mutable_protocol();
}
inline const std::string& IpcConnectionContextProto::_internal_protocol() const {
  return protocol_.Get();
}
inline void IpcConnectionContextProto::_internal_set_protocol(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  protocol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void IpcConnectionContextProto::set_protocol(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  protocol_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hadoop.common.IpcConnectionContextProto.protocol)
}
inline void IpcConnectionContextProto::set_protocol(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  protocol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hadoop.common.IpcConnectionContextProto.protocol)
}
inline void IpcConnectionContextProto::set_protocol(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  protocol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hadoop.common.IpcConnectionContextProto.protocol)
}
inline std::string* IpcConnectionContextProto::_internal_mutable_protocol() {
  _has_bits_[0] |= 0x00000001u;
  return protocol_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* IpcConnectionContextProto::release_protocol() {
  // @@protoc_insertion_point(field_release:hadoop.common.IpcConnectionContextProto.protocol)
  if (!_internal_has_protocol()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return protocol_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void IpcConnectionContextProto::set_allocated_protocol(std::string* protocol) {
  if (protocol != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  protocol_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), protocol,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.IpcConnectionContextProto.protocol)
}
inline std::string* IpcConnectionContextProto::unsafe_arena_release_protocol() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hadoop.common.IpcConnectionContextProto.protocol)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return protocol_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void IpcConnectionContextProto::unsafe_arena_set_allocated_protocol(
    std::string* protocol) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (protocol != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  protocol_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      protocol, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.IpcConnectionContextProto.protocol)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace hadoop

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto
