// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcConnectionContext.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IpcConnectionContext_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IpcConnectionContext_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IpcConnectionContext_2eproto;
namespace hadoop {
namespace common {
class IpcConnectionContextProto;
struct IpcConnectionContextProtoDefaultTypeInternal;
extern IpcConnectionContextProtoDefaultTypeInternal _IpcConnectionContextProto_default_instance_;
class UserInformationProto;
struct UserInformationProtoDefaultTypeInternal;
extern UserInformationProtoDefaultTypeInternal _UserInformationProto_default_instance_;
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> ::hadoop::common::IpcConnectionContextProto* Arena::CreateMaybeMessage<::hadoop::common::IpcConnectionContextProto>(Arena*);
template<> ::hadoop::common::UserInformationProto* Arena::CreateMaybeMessage<::hadoop::common::UserInformationProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hadoop {
namespace common {

// ===================================================================

class UserInformationProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.UserInformationProto) */ {
 public:
  inline UserInformationProto() : UserInformationProto(nullptr) {}
  ~UserInformationProto() override;
  explicit PROTOBUF_CONSTEXPR UserInformationProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserInformationProto(const UserInformationProto& from);
  UserInformationProto(UserInformationProto&& from) noexcept
    : UserInformationProto() {
    *this = ::std::move(from);
  }

  inline UserInformationProto& operator=(const UserInformationProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInformationProto& operator=(UserInformationProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserInformationProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserInformationProto* internal_default_instance() {
    return reinterpret_cast<const UserInformationProto*>(
               &_UserInformationProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserInformationProto& a, UserInformationProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInformationProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserInformationProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserInformationProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UserInformationProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UserInformationProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UserInformationProto& from) {
    UserInformationProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInformationProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.UserInformationProto";
  }
  protected:
  explicit UserInformationProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEffectiveUserFieldNumber = 1,
    kRealUserFieldNumber = 2,
  };
  // optional string effectiveUser = 1;
  bool has_effectiveuser() const;
  private:
  bool _internal_has_effectiveuser() const;
  public:
  void clear_effectiveuser();
  const std::string& effectiveuser() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_effectiveuser(ArgT0&& arg0, ArgT... args);
  std::string* mutable_effectiveuser();
  PROTOBUF_NODISCARD std::string* release_effectiveuser();
  void set_allocated_effectiveuser(std::string* effectiveuser);
  private:
  const std::string& _internal_effectiveuser() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_effectiveuser(const std::string& value);
  std::string* _internal_mutable_effectiveuser();
  public:

  // optional string realUser = 2;
  bool has_realuser() const;
  private:
  bool _internal_has_realuser() const;
  public:
  void clear_realuser();
  const std::string& realuser() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_realuser(ArgT0&& arg0, ArgT... args);
  std::string* mutable_realuser();
  PROTOBUF_NODISCARD std::string* release_realuser();
  void set_allocated_realuser(std::string* realuser);
  private:
  const std::string& _internal_realuser() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_realuser(const std::string& value);
  std::string* _internal_mutable_realuser();
  public:

  // @@protoc_insertion_point(class_scope:hadoop.common.UserInformationProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr effectiveuser_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr realuser_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_IpcConnectionContext_2eproto;
};
// -------------------------------------------------------------------

class IpcConnectionContextProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.IpcConnectionContextProto) */ {
 public:
  inline IpcConnectionContextProto() : IpcConnectionContextProto(nullptr) {}
  ~IpcConnectionContextProto() override;
  explicit PROTOBUF_CONSTEXPR IpcConnectionContextProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IpcConnectionContextProto(const IpcConnectionContextProto& from);
  IpcConnectionContextProto(IpcConnectionContextProto&& from) noexcept
    : IpcConnectionContextProto() {
    *this = ::std::move(from);
  }

  inline IpcConnectionContextProto& operator=(const IpcConnectionContextProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline IpcConnectionContextProto& operator=(IpcConnectionContextProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IpcConnectionContextProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const IpcConnectionContextProto* internal_default_instance() {
    return reinterpret_cast<const IpcConnectionContextProto*>(
               &_IpcConnectionContextProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IpcConnectionContextProto& a, IpcConnectionContextProto& b) {
    a.Swap(&b);
  }
  inline void Swap(IpcConnectionContextProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IpcConnectionContextProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IpcConnectionContextProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IpcConnectionContextProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IpcConnectionContextProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IpcConnectionContextProto& from) {
    IpcConnectionContextProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IpcConnectionContextProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.IpcConnectionContextProto";
  }
  protected:
  explicit IpcConnectionContextProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProtocolFieldNumber = 3,
    kUserInfoFieldNumber = 2,
  };
  // optional string protocol = 3;
  bool has_protocol() const;
  private:
  bool _internal_has_protocol() const;
  public:
  void clear_protocol();
  const std::string& protocol() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_protocol(ArgT0&& arg0, ArgT... args);
  std::string* mutable_protocol();
  PROTOBUF_NODISCARD std::string* release_protocol();
  void set_allocated_protocol(std::string* protocol);
  private:
  const std::string& _internal_protocol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const std::string& value);
  std::string* _internal_mutable_protocol();
  public:

  // optional .hadoop.common.UserInformationProto userInfo = 2;
  bool has_userinfo() const;
  private:
  bool _internal_has_userinfo() const;
  public:
  void clear_userinfo();
  const ::hadoop::common::UserInformationProto& userinfo() const;
  PROTOBUF_NODISCARD ::hadoop::common::UserInformationProto* release_userinfo();
  ::hadoop::common::UserInformationProto* mutable_userinfo();
  void set_allocated_userinfo(::hadoop::common::UserInformationProto* userinfo);
  private:
  const ::hadoop::common::UserInformationProto& _internal_userinfo() const;
  ::hadoop::common::UserInformationProto* _internal_mutable_userinfo();
  public:
  void unsafe_arena_set_allocated_userinfo(
      ::hadoop::common::UserInformationProto* userinfo);
  ::hadoop::common::UserInformationProto* unsafe_arena_release_userinfo();

  // @@protoc_insertion_point(class_scope:hadoop.common.IpcConnectionContextProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protocol_;
    ::hadoop::common::UserInformationProto* userinfo_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_IpcConnectionContext_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInformationProto

// optional string effectiveUser = 1;
inline bool UserInformationProto::_internal_has_effectiveuser() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UserInformationProto::has_effectiveuser() const {
  return _internal_has_effectiveuser();
}
inline void UserInformationProto::clear_effectiveuser() {
  _impl_.effectiveuser_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UserInformationProto::effectiveuser() const {
  // @@protoc_insertion_point(field_get:hadoop.common.UserInformationProto.effectiveUser)
  return _internal_effectiveuser();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInformationProto::set_effectiveuser(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.effectiveuser_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.UserInformationProto.effectiveUser)
}
inline std::string* UserInformationProto::mutable_effectiveuser() {
  std::string* _s = _internal_mutable_effectiveuser();
  // @@protoc_insertion_point(field_mutable:hadoop.common.UserInformationProto.effectiveUser)
  return _s;
}
inline const std::string& UserInformationProto::_internal_effectiveuser() const {
  return _impl_.effectiveuser_.Get();
}
inline void UserInformationProto::_internal_set_effectiveuser(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.effectiveuser_.Set(value, GetArenaForAllocation());
}
inline std::string* UserInformationProto::_internal_mutable_effectiveuser() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.effectiveuser_.Mutable(GetArenaForAllocation());
}
inline std::string* UserInformationProto::release_effectiveuser() {
  // @@protoc_insertion_point(field_release:hadoop.common.UserInformationProto.effectiveUser)
  if (!_internal_has_effectiveuser()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.effectiveuser_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.effectiveuser_.IsDefault()) {
    _impl_.effectiveuser_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void UserInformationProto::set_allocated_effectiveuser(std::string* effectiveuser) {
  if (effectiveuser != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.effectiveuser_.SetAllocated(effectiveuser, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.effectiveuser_.IsDefault()) {
    _impl_.effectiveuser_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.UserInformationProto.effectiveUser)
}

// optional string realUser = 2;
inline bool UserInformationProto::_internal_has_realuser() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UserInformationProto::has_realuser() const {
  return _internal_has_realuser();
}
inline void UserInformationProto::clear_realuser() {
  _impl_.realuser_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& UserInformationProto::realuser() const {
  // @@protoc_insertion_point(field_get:hadoop.common.UserInformationProto.realUser)
  return _internal_realuser();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void UserInformationProto::set_realuser(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.realuser_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.UserInformationProto.realUser)
}
inline std::string* UserInformationProto::mutable_realuser() {
  std::string* _s = _internal_mutable_realuser();
  // @@protoc_insertion_point(field_mutable:hadoop.common.UserInformationProto.realUser)
  return _s;
}
inline const std::string& UserInformationProto::_internal_realuser() const {
  return _impl_.realuser_.Get();
}
inline void UserInformationProto::_internal_set_realuser(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.realuser_.Set(value, GetArenaForAllocation());
}
inline std::string* UserInformationProto::_internal_mutable_realuser() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.realuser_.Mutable(GetArenaForAllocation());
}
inline std::string* UserInformationProto::release_realuser() {
  // @@protoc_insertion_point(field_release:hadoop.common.UserInformationProto.realUser)
  if (!_internal_has_realuser()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.realuser_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realuser_.IsDefault()) {
    _impl_.realuser_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void UserInformationProto::set_allocated_realuser(std::string* realuser) {
  if (realuser != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.realuser_.SetAllocated(realuser, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realuser_.IsDefault()) {
    _impl_.realuser_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.UserInformationProto.realUser)
}

// -------------------------------------------------------------------

// IpcConnectionContextProto

// optional .hadoop.common.UserInformationProto userInfo = 2;
inline bool IpcConnectionContextProto::_internal_has_userinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.userinfo_ != nullptr);
  return value;
}
inline bool IpcConnectionContextProto::has_userinfo() const {
  return _internal_has_userinfo();
}
inline void IpcConnectionContextProto::clear_userinfo() {
  if (_impl_.userinfo_ != nullptr) _impl_.userinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::hadoop::common::UserInformationProto& IpcConnectionContextProto::_internal_userinfo() const {
  const ::hadoop::common::UserInformationProto* p = _impl_.userinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::hadoop::common::UserInformationProto&>(
      ::hadoop::common::_UserInformationProto_default_instance_);
}
inline const ::hadoop::common::UserInformationProto& IpcConnectionContextProto::userinfo() const {
  // @@protoc_insertion_point(field_get:hadoop.common.IpcConnectionContextProto.userInfo)
  return _internal_userinfo();
}
inline void IpcConnectionContextProto::unsafe_arena_set_allocated_userinfo(
    ::hadoop::common::UserInformationProto* userinfo) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.userinfo_);
  }
  _impl_.userinfo_ = userinfo;
  if (userinfo) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hadoop.common.IpcConnectionContextProto.userInfo)
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::release_userinfo() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::hadoop::common::UserInformationProto* temp = _impl_.userinfo_;
  _impl_.userinfo_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::unsafe_arena_release_userinfo() {
  // @@protoc_insertion_point(field_release:hadoop.common.IpcConnectionContextProto.userInfo)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::hadoop::common::UserInformationProto* temp = _impl_.userinfo_;
  _impl_.userinfo_ = nullptr;
  return temp;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::_internal_mutable_userinfo() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.userinfo_ == nullptr) {
    auto* p = CreateMaybeMessage<::hadoop::common::UserInformationProto>(GetArenaForAllocation());
    _impl_.userinfo_ = p;
  }
  return _impl_.userinfo_;
}
inline ::hadoop::common::UserInformationProto* IpcConnectionContextProto::mutable_userinfo() {
  ::hadoop::common::UserInformationProto* _msg = _internal_mutable_userinfo();
  // @@protoc_insertion_point(field_mutable:hadoop.common.IpcConnectionContextProto.userInfo)
  return _msg;
}
inline void IpcConnectionContextProto::set_allocated_userinfo(::hadoop::common::UserInformationProto* userinfo) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.userinfo_;
  }
  if (userinfo) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(userinfo);
    if (message_arena != submessage_arena) {
      userinfo = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, userinfo, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.userinfo_ = userinfo;
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.IpcConnectionContextProto.userInfo)
}

// optional string protocol = 3;
inline bool IpcConnectionContextProto::_internal_has_protocol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IpcConnectionContextProto::has_protocol() const {
  return _internal_has_protocol();
}
inline void IpcConnectionContextProto::clear_protocol() {
  _impl_.protocol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& IpcConnectionContextProto::protocol() const {
  // @@protoc_insertion_point(field_get:hadoop.common.IpcConnectionContextProto.protocol)
  return _internal_protocol();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IpcConnectionContextProto::set_protocol(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.protocol_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.IpcConnectionContextProto.protocol)
}
inline std::string* IpcConnectionContextProto::mutable_protocol() {
  std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:hadoop.common.IpcConnectionContextProto.protocol)
  return _s;
}
inline const std::string& IpcConnectionContextProto::_internal_protocol() const {
  return _impl_.protocol_.Get();
}
inline void IpcConnectionContextProto::_internal_set_protocol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.protocol_.Set(value, GetArenaForAllocation());
}
inline std::string* IpcConnectionContextProto::_internal_mutable_protocol() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.protocol_.Mutable(GetArenaForAllocation());
}
inline std::string* IpcConnectionContextProto::release_protocol() {
  // @@protoc_insertion_point(field_release:hadoop.common.IpcConnectionContextProto.protocol)
  if (!_internal_has_protocol()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.protocol_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void IpcConnectionContextProto::set_allocated_protocol(std::string* protocol) {
  if (protocol != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.protocol_.SetAllocated(protocol, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.IpcConnectionContextProto.protocol)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace hadoop

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IpcConnectionContext_2eproto
