// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcConnectionContext.proto

#include "IpcConnectionContext.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hadoop {
namespace common {
PROTOBUF_CONSTEXPR UserInformationProto::UserInformationProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.effectiveuser_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.realuser_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct UserInformationProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserInformationProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserInformationProtoDefaultTypeInternal() {}
  union {
    UserInformationProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserInformationProtoDefaultTypeInternal _UserInformationProto_default_instance_;
PROTOBUF_CONSTEXPR IpcConnectionContextProto::IpcConnectionContextProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.protocol_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.userinfo_)*/nullptr} {}
struct IpcConnectionContextProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IpcConnectionContextProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IpcConnectionContextProtoDefaultTypeInternal() {}
  union {
    IpcConnectionContextProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IpcConnectionContextProtoDefaultTypeInternal _IpcConnectionContextProto_default_instance_;
}  // namespace common
}  // namespace hadoop
static ::_pb::Metadata file_level_metadata_IpcConnectionContext_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_IpcConnectionContext_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_IpcConnectionContext_2eproto = nullptr;

const uint32_t TableStruct_IpcConnectionContext_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _impl_.effectiveuser_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _impl_.realuser_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _impl_.userinfo_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _impl_.protocol_),
  1,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::hadoop::common::UserInformationProto)},
  { 10, 18, -1, sizeof(::hadoop::common::IpcConnectionContextProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hadoop::common::_UserInformationProto_default_instance_._instance,
  &::hadoop::common::_IpcConnectionContextProto_default_instance_._instance,
};

const char descriptor_table_protodef_IpcConnectionContext_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032IpcConnectionContext.proto\022\rhadoop.com"
  "mon\"\?\n\024UserInformationProto\022\025\n\reffective"
  "User\030\001 \001(\t\022\020\n\010realUser\030\002 \001(\t\"d\n\031IpcConne"
  "ctionContextProto\0225\n\010userInfo\030\002 \001(\0132#.ha"
  "doop.common.UserInformationProto\022\020\n\010prot"
  "ocol\030\003 \001(\tB\?\n\036org.apache.hadoop.ipc.prot"
  "obufB\032IpcConnectionContextProtos\240\001\001"
  ;
static ::_pbi::once_flag descriptor_table_IpcConnectionContext_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_IpcConnectionContext_2eproto = {
    false, false, 275, descriptor_table_protodef_IpcConnectionContext_2eproto,
    "IpcConnectionContext.proto",
    &descriptor_table_IpcConnectionContext_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_IpcConnectionContext_2eproto::offsets,
    file_level_metadata_IpcConnectionContext_2eproto, file_level_enum_descriptors_IpcConnectionContext_2eproto,
    file_level_service_descriptors_IpcConnectionContext_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_IpcConnectionContext_2eproto_getter() {
  return &descriptor_table_IpcConnectionContext_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_IpcConnectionContext_2eproto(&descriptor_table_IpcConnectionContext_2eproto);
namespace hadoop {
namespace common {

// ===================================================================

class UserInformationProto::_Internal {
 public:
  using HasBits = decltype(std::declval<UserInformationProto>()._impl_._has_bits_);
  static void set_has_effectiveuser(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_realuser(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

UserInformationProto::UserInformationProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.UserInformationProto)
}
UserInformationProto::UserInformationProto(const UserInformationProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UserInformationProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.effectiveuser_){}
    , decltype(_impl_.realuser_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.effectiveuser_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.effectiveuser_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_effectiveuser()) {
    _this->_impl_.effectiveuser_.Set(from._internal_effectiveuser(), 
      _this->GetArenaForAllocation());
  }
  _impl_.realuser_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.realuser_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_realuser()) {
    _this->_impl_.realuser_.Set(from._internal_realuser(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.UserInformationProto)
}

inline void UserInformationProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.effectiveuser_){}
    , decltype(_impl_.realuser_){}
  };
  _impl_.effectiveuser_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.effectiveuser_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.realuser_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.realuser_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UserInformationProto::~UserInformationProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.UserInformationProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UserInformationProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.effectiveuser_.Destroy();
  _impl_.realuser_.Destroy();
}

void UserInformationProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UserInformationProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.UserInformationProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.effectiveuser_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.realuser_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UserInformationProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string effectiveUser = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_effectiveuser();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.UserInformationProto.effectiveUser");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string realUser = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_realuser();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.UserInformationProto.realUser");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UserInformationProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.UserInformationProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string effectiveUser = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_effectiveuser().data(), static_cast<int>(this->_internal_effectiveuser().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.UserInformationProto.effectiveUser");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_effectiveuser(), target);
  }

  // optional string realUser = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_realuser().data(), static_cast<int>(this->_internal_realuser().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.UserInformationProto.realUser");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_realuser(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.UserInformationProto)
  return target;
}

size_t UserInformationProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.UserInformationProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string effectiveUser = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_effectiveuser());
    }

    // optional string realUser = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_realuser());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UserInformationProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UserInformationProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UserInformationProto::GetClassData() const { return &_class_data_; }


void UserInformationProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UserInformationProto*>(&to_msg);
  auto& from = static_cast<const UserInformationProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.UserInformationProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_effectiveuser(from._internal_effectiveuser());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_realuser(from._internal_realuser());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UserInformationProto::CopyFrom(const UserInformationProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.UserInformationProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserInformationProto::IsInitialized() const {
  return true;
}

void UserInformationProto::InternalSwap(UserInformationProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.effectiveuser_, lhs_arena,
      &other->_impl_.effectiveuser_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.realuser_, lhs_arena,
      &other->_impl_.realuser_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata UserInformationProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_IpcConnectionContext_2eproto_getter, &descriptor_table_IpcConnectionContext_2eproto_once,
      file_level_metadata_IpcConnectionContext_2eproto[0]);
}

// ===================================================================

class IpcConnectionContextProto::_Internal {
 public:
  using HasBits = decltype(std::declval<IpcConnectionContextProto>()._impl_._has_bits_);
  static const ::hadoop::common::UserInformationProto& userinfo(const IpcConnectionContextProto* msg);
  static void set_has_userinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_protocol(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::hadoop::common::UserInformationProto&
IpcConnectionContextProto::_Internal::userinfo(const IpcConnectionContextProto* msg) {
  return *msg->_impl_.userinfo_;
}
IpcConnectionContextProto::IpcConnectionContextProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.IpcConnectionContextProto)
}
IpcConnectionContextProto::IpcConnectionContextProto(const IpcConnectionContextProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IpcConnectionContextProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.protocol_){}
    , decltype(_impl_.userinfo_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.protocol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.protocol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_protocol()) {
    _this->_impl_.protocol_.Set(from._internal_protocol(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_userinfo()) {
    _this->_impl_.userinfo_ = new ::hadoop::common::UserInformationProto(*from._impl_.userinfo_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.IpcConnectionContextProto)
}

inline void IpcConnectionContextProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.protocol_){}
    , decltype(_impl_.userinfo_){nullptr}
  };
  _impl_.protocol_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.protocol_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

IpcConnectionContextProto::~IpcConnectionContextProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.IpcConnectionContextProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IpcConnectionContextProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.protocol_.Destroy();
  if (this != internal_default_instance()) delete _impl_.userinfo_;
}

void IpcConnectionContextProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IpcConnectionContextProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.IpcConnectionContextProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.protocol_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.userinfo_ != nullptr);
      _impl_.userinfo_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IpcConnectionContextProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .hadoop.common.UserInformationProto userInfo = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_userinfo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string protocol = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_protocol();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.IpcConnectionContextProto.protocol");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IpcConnectionContextProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.IpcConnectionContextProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .hadoop.common.UserInformationProto userInfo = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::userinfo(this),
        _Internal::userinfo(this).GetCachedSize(), target, stream);
  }

  // optional string protocol = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_protocol().data(), static_cast<int>(this->_internal_protocol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.IpcConnectionContextProto.protocol");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_protocol(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.IpcConnectionContextProto)
  return target;
}

size_t IpcConnectionContextProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.IpcConnectionContextProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string protocol = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_protocol());
    }

    // optional .hadoop.common.UserInformationProto userInfo = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.userinfo_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IpcConnectionContextProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IpcConnectionContextProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IpcConnectionContextProto::GetClassData() const { return &_class_data_; }


void IpcConnectionContextProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IpcConnectionContextProto*>(&to_msg);
  auto& from = static_cast<const IpcConnectionContextProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.IpcConnectionContextProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_protocol(from._internal_protocol());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_userinfo()->::hadoop::common::UserInformationProto::MergeFrom(
          from._internal_userinfo());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IpcConnectionContextProto::CopyFrom(const IpcConnectionContextProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.IpcConnectionContextProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IpcConnectionContextProto::IsInitialized() const {
  return true;
}

void IpcConnectionContextProto::InternalSwap(IpcConnectionContextProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.protocol_, lhs_arena,
      &other->_impl_.protocol_, rhs_arena
  );
  swap(_impl_.userinfo_, other->_impl_.userinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IpcConnectionContextProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_IpcConnectionContext_2eproto_getter, &descriptor_table_IpcConnectionContext_2eproto_once,
      file_level_metadata_IpcConnectionContext_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hadoop::common::UserInformationProto*
Arena::CreateMaybeMessage< ::hadoop::common::UserInformationProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::UserInformationProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::IpcConnectionContextProto*
Arena::CreateMaybeMessage< ::hadoop::common::IpcConnectionContextProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::IpcConnectionContextProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
