// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcConnectionContext.proto

#include "IpcConnectionContext.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_IpcConnectionContext_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UserInformationProto_IpcConnectionContext_2eproto;
namespace hadoop {
namespace common {
class UserInformationProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UserInformationProto> _instance;
} _UserInformationProto_default_instance_;
class IpcConnectionContextProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IpcConnectionContextProto> _instance;
} _IpcConnectionContextProto_default_instance_;
}  // namespace common
}  // namespace hadoop
static void InitDefaultsscc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hadoop::common::_IpcConnectionContextProto_default_instance_;
    new (ptr) ::hadoop::common::IpcConnectionContextProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hadoop::common::IpcConnectionContextProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto}, {
      &scc_info_UserInformationProto_IpcConnectionContext_2eproto.base,}};

static void InitDefaultsscc_info_UserInformationProto_IpcConnectionContext_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hadoop::common::_UserInformationProto_default_instance_;
    new (ptr) ::hadoop::common::UserInformationProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hadoop::common::UserInformationProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UserInformationProto_IpcConnectionContext_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_UserInformationProto_IpcConnectionContext_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_IpcConnectionContext_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_IpcConnectionContext_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_IpcConnectionContext_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_IpcConnectionContext_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, effectiveuser_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::UserInformationProto, realuser_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, userinfo_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::IpcConnectionContextProto, protocol_),
  1,
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::hadoop::common::UserInformationProto)},
  { 9, 16, sizeof(::hadoop::common::IpcConnectionContextProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::hadoop::common::_UserInformationProto_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::hadoop::common::_IpcConnectionContextProto_default_instance_),
};

const char descriptor_table_protodef_IpcConnectionContext_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032IpcConnectionContext.proto\022\rhadoop.com"
  "mon\"\?\n\024UserInformationProto\022\025\n\reffective"
  "User\030\001 \001(\t\022\020\n\010realUser\030\002 \001(\t\"d\n\031IpcConne"
  "ctionContextProto\0225\n\010userInfo\030\002 \001(\0132#.ha"
  "doop.common.UserInformationProto\022\020\n\010prot"
  "ocol\030\003 \001(\tB\?\n\036org.apache.hadoop.ipc.prot"
  "obufB\032IpcConnectionContextProtos\240\001\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_IpcConnectionContext_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_IpcConnectionContext_2eproto_sccs[2] = {
  &scc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto.base,
  &scc_info_UserInformationProto_IpcConnectionContext_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_IpcConnectionContext_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IpcConnectionContext_2eproto = {
  false, false, descriptor_table_protodef_IpcConnectionContext_2eproto, "IpcConnectionContext.proto", 275,
  &descriptor_table_IpcConnectionContext_2eproto_once, descriptor_table_IpcConnectionContext_2eproto_sccs, descriptor_table_IpcConnectionContext_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_IpcConnectionContext_2eproto::offsets,
  file_level_metadata_IpcConnectionContext_2eproto, 2, file_level_enum_descriptors_IpcConnectionContext_2eproto, file_level_service_descriptors_IpcConnectionContext_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_IpcConnectionContext_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_IpcConnectionContext_2eproto)), true);
namespace hadoop {
namespace common {

// ===================================================================

void UserInformationProto::InitAsDefaultInstance() {
}
class UserInformationProto::_Internal {
 public:
  using HasBits = decltype(std::declval<UserInformationProto>()._has_bits_);
  static void set_has_effectiveuser(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_realuser(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

UserInformationProto::UserInformationProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.UserInformationProto)
}
UserInformationProto::UserInformationProto(const UserInformationProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  effectiveuser_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_effectiveuser()) {
    effectiveuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_effectiveuser(),
      GetArena());
  }
  realuser_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_realuser()) {
    realuser_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_realuser(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.UserInformationProto)
}

void UserInformationProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UserInformationProto_IpcConnectionContext_2eproto.base);
  effectiveuser_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  realuser_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

UserInformationProto::~UserInformationProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.UserInformationProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UserInformationProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  effectiveuser_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  realuser_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void UserInformationProto::ArenaDtor(void* object) {
  UserInformationProto* _this = reinterpret_cast< UserInformationProto* >(object);
  (void)_this;
}
void UserInformationProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UserInformationProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UserInformationProto& UserInformationProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UserInformationProto_IpcConnectionContext_2eproto.base);
  return *internal_default_instance();
}


void UserInformationProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.UserInformationProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      effectiveuser_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      realuser_.ClearNonDefaultToEmpty();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UserInformationProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string effectiveUser = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_effectiveuser();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "hadoop.common.UserInformationProto.effectiveUser");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string realUser = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_realuser();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "hadoop.common.UserInformationProto.realUser");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UserInformationProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.UserInformationProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string effectiveUser = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_effectiveuser().data(), static_cast<int>(this->_internal_effectiveuser().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.UserInformationProto.effectiveUser");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_effectiveuser(), target);
  }

  // optional string realUser = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_realuser().data(), static_cast<int>(this->_internal_realuser().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.UserInformationProto.realUser");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_realuser(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.UserInformationProto)
  return target;
}

size_t UserInformationProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.UserInformationProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string effectiveUser = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_effectiveuser());
    }

    // optional string realUser = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_realuser());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserInformationProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hadoop.common.UserInformationProto)
  GOOGLE_DCHECK_NE(&from, this);
  const UserInformationProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UserInformationProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hadoop.common.UserInformationProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hadoop.common.UserInformationProto)
    MergeFrom(*source);
  }
}

void UserInformationProto::MergeFrom(const UserInformationProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.UserInformationProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_effectiveuser(from._internal_effectiveuser());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_realuser(from._internal_realuser());
    }
  }
}

void UserInformationProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hadoop.common.UserInformationProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserInformationProto::CopyFrom(const UserInformationProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.UserInformationProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserInformationProto::IsInitialized() const {
  return true;
}

void UserInformationProto::InternalSwap(UserInformationProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  effectiveuser_.Swap(&other->effectiveuser_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  realuser_.Swap(&other->realuser_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata UserInformationProto::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void IpcConnectionContextProto::InitAsDefaultInstance() {
  ::hadoop::common::_IpcConnectionContextProto_default_instance_._instance.get_mutable()->userinfo_ = const_cast< ::hadoop::common::UserInformationProto*>(
      ::hadoop::common::UserInformationProto::internal_default_instance());
}
class IpcConnectionContextProto::_Internal {
 public:
  using HasBits = decltype(std::declval<IpcConnectionContextProto>()._has_bits_);
  static const ::hadoop::common::UserInformationProto& userinfo(const IpcConnectionContextProto* msg);
  static void set_has_userinfo(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_protocol(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::hadoop::common::UserInformationProto&
IpcConnectionContextProto::_Internal::userinfo(const IpcConnectionContextProto* msg) {
  return *msg->userinfo_;
}
IpcConnectionContextProto::IpcConnectionContextProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.IpcConnectionContextProto)
}
IpcConnectionContextProto::IpcConnectionContextProto(const IpcConnectionContextProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  protocol_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_protocol()) {
    protocol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_protocol(),
      GetArena());
  }
  if (from._internal_has_userinfo()) {
    userinfo_ = new ::hadoop::common::UserInformationProto(*from.userinfo_);
  } else {
    userinfo_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.IpcConnectionContextProto)
}

void IpcConnectionContextProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto.base);
  protocol_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  userinfo_ = nullptr;
}

IpcConnectionContextProto::~IpcConnectionContextProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.IpcConnectionContextProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IpcConnectionContextProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  protocol_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete userinfo_;
}

void IpcConnectionContextProto::ArenaDtor(void* object) {
  IpcConnectionContextProto* _this = reinterpret_cast< IpcConnectionContextProto* >(object);
  (void)_this;
}
void IpcConnectionContextProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IpcConnectionContextProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IpcConnectionContextProto& IpcConnectionContextProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IpcConnectionContextProto_IpcConnectionContext_2eproto.base);
  return *internal_default_instance();
}


void IpcConnectionContextProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.IpcConnectionContextProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      protocol_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(userinfo_ != nullptr);
      userinfo_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IpcConnectionContextProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .hadoop.common.UserInformationProto userInfo = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_userinfo(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string protocol = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_protocol();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "hadoop.common.IpcConnectionContextProto.protocol");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IpcConnectionContextProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.IpcConnectionContextProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .hadoop.common.UserInformationProto userInfo = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::userinfo(this), target, stream);
  }

  // optional string protocol = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_protocol().data(), static_cast<int>(this->_internal_protocol().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.IpcConnectionContextProto.protocol");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_protocol(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.IpcConnectionContextProto)
  return target;
}

size_t IpcConnectionContextProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.IpcConnectionContextProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string protocol = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_protocol());
    }

    // optional .hadoop.common.UserInformationProto userInfo = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *userinfo_);
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IpcConnectionContextProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hadoop.common.IpcConnectionContextProto)
  GOOGLE_DCHECK_NE(&from, this);
  const IpcConnectionContextProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IpcConnectionContextProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hadoop.common.IpcConnectionContextProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hadoop.common.IpcConnectionContextProto)
    MergeFrom(*source);
  }
}

void IpcConnectionContextProto::MergeFrom(const IpcConnectionContextProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.IpcConnectionContextProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_protocol(from._internal_protocol());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_userinfo()->::hadoop::common::UserInformationProto::MergeFrom(from._internal_userinfo());
    }
  }
}

void IpcConnectionContextProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hadoop.common.IpcConnectionContextProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IpcConnectionContextProto::CopyFrom(const IpcConnectionContextProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.IpcConnectionContextProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IpcConnectionContextProto::IsInitialized() const {
  return true;
}

void IpcConnectionContextProto::InternalSwap(IpcConnectionContextProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  protocol_.Swap(&other->protocol_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(userinfo_, other->userinfo_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IpcConnectionContextProto::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hadoop::common::UserInformationProto* Arena::CreateMaybeMessage< ::hadoop::common::UserInformationProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::UserInformationProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::IpcConnectionContextProto* Arena::CreateMaybeMessage< ::hadoop::common::IpcConnectionContextProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::IpcConnectionContextProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
