// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufRpcEngine.proto

#include "ProtobufRpcEngine.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hadoop {
namespace common {
PROTOBUF_CONSTEXPR RequestHeaderProto::RequestHeaderProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._extensions_)*/{}
  , /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.methodname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.declaringclassprotocolname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.clientprotocolversion_)*/uint64_t{0u}} {}
struct RequestHeaderProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestHeaderProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestHeaderProtoDefaultTypeInternal() {}
  union {
    RequestHeaderProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestHeaderProtoDefaultTypeInternal _RequestHeaderProto_default_instance_;
}  // namespace common
}  // namespace hadoop
static ::_pb::Metadata file_level_metadata_ProtobufRpcEngine_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ProtobufRpcEngine_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ProtobufRpcEngine_2eproto = nullptr;

const uint32_t TableStruct_ProtobufRpcEngine_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _internal_metadata_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _impl_._extensions_),
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _impl_.methodname_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _impl_.declaringclassprotocolname_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RequestHeaderProto, _impl_.clientprotocolversion_),
  0,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::hadoop::common::RequestHeaderProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hadoop::common::_RequestHeaderProto_default_instance_._instance,
};

const char descriptor_table_protodef_ProtobufRpcEngine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027ProtobufRpcEngine.proto\022\rhadoop.common"
  "\"v\n\022RequestHeaderProto\022\022\n\nmethodName\030\001 \002"
  "(\t\022\"\n\032declaringClassProtocolName\030\002 \002(\t\022\035"
  "\n\025clientProtocolVersion\030\003 \002(\004*\t\010\350\007\020\200\200\200\200\002"
  "B<\n\036org.apache.hadoop.ipc.protobufB\027Prot"
  "obufRpcEngineProtos\240\001\001"
  ;
static ::_pbi::once_flag descriptor_table_ProtobufRpcEngine_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ProtobufRpcEngine_2eproto = {
    false, false, 222, descriptor_table_protodef_ProtobufRpcEngine_2eproto,
    "ProtobufRpcEngine.proto",
    &descriptor_table_ProtobufRpcEngine_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ProtobufRpcEngine_2eproto::offsets,
    file_level_metadata_ProtobufRpcEngine_2eproto, file_level_enum_descriptors_ProtobufRpcEngine_2eproto,
    file_level_service_descriptors_ProtobufRpcEngine_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ProtobufRpcEngine_2eproto_getter() {
  return &descriptor_table_ProtobufRpcEngine_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ProtobufRpcEngine_2eproto(&descriptor_table_ProtobufRpcEngine_2eproto);
namespace hadoop {
namespace common {

// ===================================================================

class RequestHeaderProto::_Internal {
 public:
  using HasBits = decltype(std::declval<RequestHeaderProto>()._impl_._has_bits_);
  static void set_has_methodname(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_declaringclassprotocolname(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_clientprotocolversion(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

RequestHeaderProto::RequestHeaderProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.RequestHeaderProto)
}
RequestHeaderProto::RequestHeaderProto(const RequestHeaderProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RequestHeaderProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._extensions_)*/{}
    , decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.methodname_){}
    , decltype(_impl_.declaringclassprotocolname_){}
    , decltype(_impl_.clientprotocolversion_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _impl_.methodname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.methodname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_methodname()) {
    _this->_impl_.methodname_.Set(from._internal_methodname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.declaringclassprotocolname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.declaringclassprotocolname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_declaringclassprotocolname()) {
    _this->_impl_.declaringclassprotocolname_.Set(from._internal_declaringclassprotocolname(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.clientprotocolversion_ = from._impl_.clientprotocolversion_;
  // @@protoc_insertion_point(copy_constructor:hadoop.common.RequestHeaderProto)
}

inline void RequestHeaderProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._extensions_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.methodname_){}
    , decltype(_impl_.declaringclassprotocolname_){}
    , decltype(_impl_.clientprotocolversion_){uint64_t{0u}}
  };
  _impl_.methodname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.methodname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.declaringclassprotocolname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.declaringclassprotocolname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RequestHeaderProto::~RequestHeaderProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.RequestHeaderProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RequestHeaderProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_._extensions_.~ExtensionSet();
  _impl_.methodname_.Destroy();
  _impl_.declaringclassprotocolname_.Destroy();
}

void RequestHeaderProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RequestHeaderProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.RequestHeaderProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.methodname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.declaringclassprotocolname_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.clientprotocolversion_ = uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RequestHeaderProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string methodName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_methodname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.RequestHeaderProto.methodName");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required string declaringClassProtocolName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_declaringclassprotocolname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.RequestHeaderProto.declaringClassProtocolName");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required uint64 clientProtocolVersion = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_clientprotocolversion(&has_bits);
          _impl_.clientprotocolversion_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    if ((8000u <= tag)) {
      ptr = _impl_._extensions_.ParseField(tag, ptr, internal_default_instance(), &_internal_metadata_, ctx);
      CHK_(ptr != nullptr);
      continue;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RequestHeaderProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.RequestHeaderProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string methodName = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_methodname().data(), static_cast<int>(this->_internal_methodname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.RequestHeaderProto.methodName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_methodname(), target);
  }

  // required string declaringClassProtocolName = 2;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_declaringclassprotocolname().data(), static_cast<int>(this->_internal_declaringclassprotocolname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.RequestHeaderProto.declaringClassProtocolName");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_declaringclassprotocolname(), target);
  }

  // required uint64 clientProtocolVersion = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_clientprotocolversion(), target);
  }

  // Extension range [1000, 536870912)
  target = _impl_._extensions_._InternalSerialize(
  internal_default_instance(), 1000, 536870912, target, stream);

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.RequestHeaderProto)
  return target;
}

size_t RequestHeaderProto::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:hadoop.common.RequestHeaderProto)
  size_t total_size = 0;

  if (_internal_has_methodname()) {
    // required string methodName = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_methodname());
  }

  if (_internal_has_declaringclassprotocolname()) {
    // required string declaringClassProtocolName = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_declaringclassprotocolname());
  }

  if (_internal_has_clientprotocolversion()) {
    // required uint64 clientProtocolVersion = 3;
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_clientprotocolversion());
  }

  return total_size;
}
size_t RequestHeaderProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.RequestHeaderProto)
  size_t total_size = 0;

  total_size += _impl_._extensions_.ByteSize();

  if (((_impl_._has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string methodName = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_methodname());

    // required string declaringClassProtocolName = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_declaringclassprotocolname());

    // required uint64 clientProtocolVersion = 3;
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_clientprotocolversion());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestHeaderProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RequestHeaderProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestHeaderProto::GetClassData() const { return &_class_data_; }


void RequestHeaderProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RequestHeaderProto*>(&to_msg);
  auto& from = static_cast<const RequestHeaderProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.RequestHeaderProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_methodname(from._internal_methodname());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_declaringclassprotocolname(from._internal_declaringclassprotocolname());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.clientprotocolversion_ = from._impl_.clientprotocolversion_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RequestHeaderProto::CopyFrom(const RequestHeaderProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.RequestHeaderProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestHeaderProto::IsInitialized() const {
  if (!_impl_._extensions_.IsInitialized()) {
    return false;
  }

  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void RequestHeaderProto::InternalSwap(RequestHeaderProto* other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.methodname_, lhs_arena,
      &other->_impl_.methodname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.declaringclassprotocolname_, lhs_arena,
      &other->_impl_.declaringclassprotocolname_, rhs_arena
  );
  swap(_impl_.clientprotocolversion_, other->_impl_.clientprotocolversion_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestHeaderProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProtobufRpcEngine_2eproto_getter, &descriptor_table_ProtobufRpcEngine_2eproto_once,
      file_level_metadata_ProtobufRpcEngine_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hadoop::common::RequestHeaderProto*
Arena::CreateMaybeMessage< ::hadoop::common::RequestHeaderProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::RequestHeaderProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
