// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufRpcEngine.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtobufRpcEngine_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProtobufRpcEngine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProtobufRpcEngine_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtobufRpcEngine_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProtobufRpcEngine_2eproto;
namespace hadoop {
namespace common {
class RequestHeaderProto;
struct RequestHeaderProtoDefaultTypeInternal;
extern RequestHeaderProtoDefaultTypeInternal _RequestHeaderProto_default_instance_;
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> ::hadoop::common::RequestHeaderProto* Arena::CreateMaybeMessage<::hadoop::common::RequestHeaderProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hadoop {
namespace common {

// ===================================================================

class RequestHeaderProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hadoop.common.RequestHeaderProto) */ {
 public:
  inline RequestHeaderProto() : RequestHeaderProto(nullptr) {}
  ~RequestHeaderProto() override;
  explicit PROTOBUF_CONSTEXPR RequestHeaderProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestHeaderProto(const RequestHeaderProto& from);
  RequestHeaderProto(RequestHeaderProto&& from) noexcept
    : RequestHeaderProto() {
    *this = ::std::move(from);
  }

  inline RequestHeaderProto& operator=(const RequestHeaderProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestHeaderProto& operator=(RequestHeaderProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestHeaderProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestHeaderProto* internal_default_instance() {
    return reinterpret_cast<const RequestHeaderProto*>(
               &_RequestHeaderProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RequestHeaderProto& a, RequestHeaderProto& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestHeaderProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestHeaderProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestHeaderProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestHeaderProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestHeaderProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestHeaderProto& from) {
    RequestHeaderProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestHeaderProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hadoop.common.RequestHeaderProto";
  }
  protected:
  explicit RequestHeaderProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodNameFieldNumber = 1,
    kDeclaringClassProtocolNameFieldNumber = 2,
    kClientProtocolVersionFieldNumber = 3,
  };
  // required string methodName = 1;
  bool has_methodname() const;
  private:
  bool _internal_has_methodname() const;
  public:
  void clear_methodname();
  const std::string& methodname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_methodname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_methodname();
  PROTOBUF_NODISCARD std::string* release_methodname();
  void set_allocated_methodname(std::string* methodname);
  private:
  const std::string& _internal_methodname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_methodname(const std::string& value);
  std::string* _internal_mutable_methodname();
  public:

  // required string declaringClassProtocolName = 2;
  bool has_declaringclassprotocolname() const;
  private:
  bool _internal_has_declaringclassprotocolname() const;
  public:
  void clear_declaringclassprotocolname();
  const std::string& declaringclassprotocolname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_declaringclassprotocolname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_declaringclassprotocolname();
  PROTOBUF_NODISCARD std::string* release_declaringclassprotocolname();
  void set_allocated_declaringclassprotocolname(std::string* declaringclassprotocolname);
  private:
  const std::string& _internal_declaringclassprotocolname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_declaringclassprotocolname(const std::string& value);
  std::string* _internal_mutable_declaringclassprotocolname();
  public:

  // required uint64 clientProtocolVersion = 3;
  bool has_clientprotocolversion() const;
  private:
  bool _internal_has_clientprotocolversion() const;
  public:
  void clear_clientprotocolversion();
  uint64_t clientprotocolversion() const;
  void set_clientprotocolversion(uint64_t value);
  private:
  uint64_t _internal_clientprotocolversion() const;
  void _internal_set_clientprotocolversion(uint64_t value);
  public:


  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline bool HasExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) const {

    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());

  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline int ExtensionSize(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) const {

    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) const {

    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_,
                                  id.default_value());
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {

    return _proto_TypeTraits::Mutable(id.number(), _field_type,
                                      &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);

  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);

  }
  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);

  }
  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
              RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {

    return _proto_TypeTraits::Release(id.number(), _field_type,
                                      &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {

    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      int index) const {

    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      int index) {

    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);

  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);

    return to_add;
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);

  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) const {

    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits,
            ::PROTOBUF_NAMESPACE_ID::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier<
          RequestHeaderProto, _proto_TypeTraits, _field_type, _is_packed>& id) {

    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }

  // @@protoc_insertion_point(class_scope:hadoop.common.RequestHeaderProto)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ExtensionSet _extensions_;

    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr methodname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr declaringclassprotocolname_;
    uint64_t clientprotocolversion_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtobufRpcEngine_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RequestHeaderProto

// required string methodName = 1;
inline bool RequestHeaderProto::_internal_has_methodname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RequestHeaderProto::has_methodname() const {
  return _internal_has_methodname();
}
inline void RequestHeaderProto::clear_methodname() {
  _impl_.methodname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RequestHeaderProto::methodname() const {
  // @@protoc_insertion_point(field_get:hadoop.common.RequestHeaderProto.methodName)
  return _internal_methodname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestHeaderProto::set_methodname(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.methodname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.RequestHeaderProto.methodName)
}
inline std::string* RequestHeaderProto::mutable_methodname() {
  std::string* _s = _internal_mutable_methodname();
  // @@protoc_insertion_point(field_mutable:hadoop.common.RequestHeaderProto.methodName)
  return _s;
}
inline const std::string& RequestHeaderProto::_internal_methodname() const {
  return _impl_.methodname_.Get();
}
inline void RequestHeaderProto::_internal_set_methodname(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.methodname_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestHeaderProto::_internal_mutable_methodname() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.methodname_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestHeaderProto::release_methodname() {
  // @@protoc_insertion_point(field_release:hadoop.common.RequestHeaderProto.methodName)
  if (!_internal_has_methodname()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.methodname_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.methodname_.IsDefault()) {
    _impl_.methodname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void RequestHeaderProto::set_allocated_methodname(std::string* methodname) {
  if (methodname != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.methodname_.SetAllocated(methodname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.methodname_.IsDefault()) {
    _impl_.methodname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.RequestHeaderProto.methodName)
}

// required string declaringClassProtocolName = 2;
inline bool RequestHeaderProto::_internal_has_declaringclassprotocolname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RequestHeaderProto::has_declaringclassprotocolname() const {
  return _internal_has_declaringclassprotocolname();
}
inline void RequestHeaderProto::clear_declaringclassprotocolname() {
  _impl_.declaringclassprotocolname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RequestHeaderProto::declaringclassprotocolname() const {
  // @@protoc_insertion_point(field_get:hadoop.common.RequestHeaderProto.declaringClassProtocolName)
  return _internal_declaringclassprotocolname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestHeaderProto::set_declaringclassprotocolname(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.declaringclassprotocolname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hadoop.common.RequestHeaderProto.declaringClassProtocolName)
}
inline std::string* RequestHeaderProto::mutable_declaringclassprotocolname() {
  std::string* _s = _internal_mutable_declaringclassprotocolname();
  // @@protoc_insertion_point(field_mutable:hadoop.common.RequestHeaderProto.declaringClassProtocolName)
  return _s;
}
inline const std::string& RequestHeaderProto::_internal_declaringclassprotocolname() const {
  return _impl_.declaringclassprotocolname_.Get();
}
inline void RequestHeaderProto::_internal_set_declaringclassprotocolname(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.declaringclassprotocolname_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestHeaderProto::_internal_mutable_declaringclassprotocolname() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.declaringclassprotocolname_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestHeaderProto::release_declaringclassprotocolname() {
  // @@protoc_insertion_point(field_release:hadoop.common.RequestHeaderProto.declaringClassProtocolName)
  if (!_internal_has_declaringclassprotocolname()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.declaringclassprotocolname_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.declaringclassprotocolname_.IsDefault()) {
    _impl_.declaringclassprotocolname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void RequestHeaderProto::set_allocated_declaringclassprotocolname(std::string* declaringclassprotocolname) {
  if (declaringclassprotocolname != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.declaringclassprotocolname_.SetAllocated(declaringclassprotocolname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.declaringclassprotocolname_.IsDefault()) {
    _impl_.declaringclassprotocolname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hadoop.common.RequestHeaderProto.declaringClassProtocolName)
}

// required uint64 clientProtocolVersion = 3;
inline bool RequestHeaderProto::_internal_has_clientprotocolversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RequestHeaderProto::has_clientprotocolversion() const {
  return _internal_has_clientprotocolversion();
}
inline void RequestHeaderProto::clear_clientprotocolversion() {
  _impl_.clientprotocolversion_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint64_t RequestHeaderProto::_internal_clientprotocolversion() const {
  return _impl_.clientprotocolversion_;
}
inline uint64_t RequestHeaderProto::clientprotocolversion() const {
  // @@protoc_insertion_point(field_get:hadoop.common.RequestHeaderProto.clientProtocolVersion)
  return _internal_clientprotocolversion();
}
inline void RequestHeaderProto::_internal_set_clientprotocolversion(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.clientprotocolversion_ = value;
}
inline void RequestHeaderProto::set_clientprotocolversion(uint64_t value) {
  _internal_set_clientprotocolversion(value);
  // @@protoc_insertion_point(field_set:hadoop.common.RequestHeaderProto.clientProtocolVersion)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace hadoop

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProtobufRpcEngine_2eproto
