// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Security.proto

#include "Security.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hadoop {
namespace common {
PROTOBUF_CONSTEXPR TokenProto::TokenProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.identifier_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.password_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.kind_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.service_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct TokenProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokenProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokenProtoDefaultTypeInternal() {}
  union {
    TokenProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokenProtoDefaultTypeInternal _TokenProto_default_instance_;
PROTOBUF_CONSTEXPR CredentialsKVProto::CredentialsKVProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.alias_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.secret_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.token_)*/nullptr} {}
struct CredentialsKVProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CredentialsKVProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CredentialsKVProtoDefaultTypeInternal() {}
  union {
    CredentialsKVProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CredentialsKVProtoDefaultTypeInternal _CredentialsKVProto_default_instance_;
PROTOBUF_CONSTEXPR CredentialsProto::CredentialsProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tokens_)*/{}
  , /*decltype(_impl_.secrets_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CredentialsProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CredentialsProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CredentialsProtoDefaultTypeInternal() {}
  union {
    CredentialsProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CredentialsProtoDefaultTypeInternal _CredentialsProto_default_instance_;
PROTOBUF_CONSTEXPR GetDelegationTokenRequestProto::GetDelegationTokenRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.renewer_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct GetDelegationTokenRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDelegationTokenRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDelegationTokenRequestProtoDefaultTypeInternal() {}
  union {
    GetDelegationTokenRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDelegationTokenRequestProtoDefaultTypeInternal _GetDelegationTokenRequestProto_default_instance_;
PROTOBUF_CONSTEXPR GetDelegationTokenResponseProto::GetDelegationTokenResponseProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.token_)*/nullptr} {}
struct GetDelegationTokenResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetDelegationTokenResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetDelegationTokenResponseProtoDefaultTypeInternal() {}
  union {
    GetDelegationTokenResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetDelegationTokenResponseProtoDefaultTypeInternal _GetDelegationTokenResponseProto_default_instance_;
PROTOBUF_CONSTEXPR RenewDelegationTokenRequestProto::RenewDelegationTokenRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.token_)*/nullptr} {}
struct RenewDelegationTokenRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenewDelegationTokenRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenewDelegationTokenRequestProtoDefaultTypeInternal() {}
  union {
    RenewDelegationTokenRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenewDelegationTokenRequestProtoDefaultTypeInternal _RenewDelegationTokenRequestProto_default_instance_;
PROTOBUF_CONSTEXPR RenewDelegationTokenResponseProto::RenewDelegationTokenResponseProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.newexpirytime_)*/uint64_t{0u}} {}
struct RenewDelegationTokenResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RenewDelegationTokenResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RenewDelegationTokenResponseProtoDefaultTypeInternal() {}
  union {
    RenewDelegationTokenResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RenewDelegationTokenResponseProtoDefaultTypeInternal _RenewDelegationTokenResponseProto_default_instance_;
PROTOBUF_CONSTEXPR CancelDelegationTokenRequestProto::CancelDelegationTokenRequestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.token_)*/nullptr} {}
struct CancelDelegationTokenRequestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CancelDelegationTokenRequestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CancelDelegationTokenRequestProtoDefaultTypeInternal() {}
  union {
    CancelDelegationTokenRequestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CancelDelegationTokenRequestProtoDefaultTypeInternal _CancelDelegationTokenRequestProto_default_instance_;
PROTOBUF_CONSTEXPR CancelDelegationTokenResponseProto::CancelDelegationTokenResponseProto(
    ::_pbi::ConstantInitialized) {}
struct CancelDelegationTokenResponseProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CancelDelegationTokenResponseProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CancelDelegationTokenResponseProtoDefaultTypeInternal() {}
  union {
    CancelDelegationTokenResponseProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CancelDelegationTokenResponseProtoDefaultTypeInternal _CancelDelegationTokenResponseProto_default_instance_;
}  // namespace common
}  // namespace hadoop
static ::_pb::Metadata file_level_metadata_Security_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Security_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Security_2eproto = nullptr;

const uint32_t TableStruct_Security_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _impl_.identifier_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _impl_.password_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _impl_.kind_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::TokenProto, _impl_.service_),
  0,
  1,
  2,
  3,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsKVProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsKVProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsKVProto, _impl_.alias_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsKVProto, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsKVProto, _impl_.secret_),
  0,
  2,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsProto, _impl_.tokens_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CredentialsProto, _impl_.secrets_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenRequestProto, _impl_.renewer_),
  0,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenResponseProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::GetDelegationTokenResponseProto, _impl_.token_),
  0,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenRequestProto, _impl_.token_),
  0,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenResponseProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::RenewDelegationTokenResponseProto, _impl_.newexpirytime_),
  0,
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CancelDelegationTokenRequestProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CancelDelegationTokenRequestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CancelDelegationTokenRequestProto, _impl_.token_),
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hadoop::common::CancelDelegationTokenResponseProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::hadoop::common::TokenProto)},
  { 14, 23, -1, sizeof(::hadoop::common::CredentialsKVProto)},
  { 26, -1, -1, sizeof(::hadoop::common::CredentialsProto)},
  { 34, 41, -1, sizeof(::hadoop::common::GetDelegationTokenRequestProto)},
  { 42, 49, -1, sizeof(::hadoop::common::GetDelegationTokenResponseProto)},
  { 50, 57, -1, sizeof(::hadoop::common::RenewDelegationTokenRequestProto)},
  { 58, 65, -1, sizeof(::hadoop::common::RenewDelegationTokenResponseProto)},
  { 66, 73, -1, sizeof(::hadoop::common::CancelDelegationTokenRequestProto)},
  { 74, -1, -1, sizeof(::hadoop::common::CancelDelegationTokenResponseProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hadoop::common::_TokenProto_default_instance_._instance,
  &::hadoop::common::_CredentialsKVProto_default_instance_._instance,
  &::hadoop::common::_CredentialsProto_default_instance_._instance,
  &::hadoop::common::_GetDelegationTokenRequestProto_default_instance_._instance,
  &::hadoop::common::_GetDelegationTokenResponseProto_default_instance_._instance,
  &::hadoop::common::_RenewDelegationTokenRequestProto_default_instance_._instance,
  &::hadoop::common::_RenewDelegationTokenResponseProto_default_instance_._instance,
  &::hadoop::common::_CancelDelegationTokenRequestProto_default_instance_._instance,
  &::hadoop::common::_CancelDelegationTokenResponseProto_default_instance_._instance,
};

const char descriptor_table_protodef_Security_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Security.proto\022\rhadoop.common\"Q\n\nToken"
  "Proto\022\022\n\nidentifier\030\001 \002(\014\022\020\n\010password\030\002 "
  "\002(\014\022\014\n\004kind\030\003 \002(\t\022\017\n\007service\030\004 \002(\t\"]\n\022Cr"
  "edentialsKVProto\022\r\n\005alias\030\001 \002(\t\022(\n\005token"
  "\030\002 \001(\0132\031.hadoop.common.TokenProto\022\016\n\006sec"
  "ret\030\003 \001(\014\"y\n\020CredentialsProto\0221\n\006tokens\030"
  "\001 \003(\0132!.hadoop.common.CredentialsKVProto"
  "\0222\n\007secrets\030\002 \003(\0132!.hadoop.common.Creden"
  "tialsKVProto\"1\n\036GetDelegationTokenReques"
  "tProto\022\017\n\007renewer\030\001 \002(\t\"K\n\037GetDelegation"
  "TokenResponseProto\022(\n\005token\030\001 \001(\0132\031.hado"
  "op.common.TokenProto\"L\n RenewDelegationT"
  "okenRequestProto\022(\n\005token\030\001 \002(\0132\031.hadoop"
  ".common.TokenProto\":\n!RenewDelegationTok"
  "enResponseProto\022\025\n\rnewExpiryTime\030\001 \002(\004\"M"
  "\n!CancelDelegationTokenRequestProto\022(\n\005t"
  "oken\030\001 \002(\0132\031.hadoop.common.TokenProto\"$\n"
  "\"CancelDelegationTokenResponseProtoB8\n o"
  "rg.apache.hadoop.security.protoB\016Securit"
  "yProtos\210\001\001\240\001\001"
  ;
static ::_pbi::once_flag descriptor_table_Security_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Security_2eproto = {
    false, false, 773, descriptor_table_protodef_Security_2eproto,
    "Security.proto",
    &descriptor_table_Security_2eproto_once, nullptr, 0, 9,
    schemas, file_default_instances, TableStruct_Security_2eproto::offsets,
    file_level_metadata_Security_2eproto, file_level_enum_descriptors_Security_2eproto,
    file_level_service_descriptors_Security_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Security_2eproto_getter() {
  return &descriptor_table_Security_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Security_2eproto(&descriptor_table_Security_2eproto);
namespace hadoop {
namespace common {

// ===================================================================

class TokenProto::_Internal {
 public:
  using HasBits = decltype(std::declval<TokenProto>()._impl_._has_bits_);
  static void set_has_identifier(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_password(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_kind(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_service(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000f) ^ 0x0000000f) != 0;
  }
};

TokenProto::TokenProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.TokenProto)
}
TokenProto::TokenProto(const TokenProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TokenProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.identifier_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.kind_){}
    , decltype(_impl_.service_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.identifier_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.identifier_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_identifier()) {
    _this->_impl_.identifier_.Set(from._internal_identifier(), 
      _this->GetArenaForAllocation());
  }
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_password()) {
    _this->_impl_.password_.Set(from._internal_password(), 
      _this->GetArenaForAllocation());
  }
  _impl_.kind_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.kind_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_kind()) {
    _this->_impl_.kind_.Set(from._internal_kind(), 
      _this->GetArenaForAllocation());
  }
  _impl_.service_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_service()) {
    _this->_impl_.service_.Set(from._internal_service(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.TokenProto)
}

inline void TokenProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.identifier_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.kind_){}
    , decltype(_impl_.service_){}
  };
  _impl_.identifier_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.identifier_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.kind_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.kind_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.service_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TokenProto::~TokenProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.TokenProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TokenProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.identifier_.Destroy();
  _impl_.password_.Destroy();
  _impl_.kind_.Destroy();
  _impl_.service_.Destroy();
}

void TokenProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TokenProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.TokenProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.identifier_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.kind_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.service_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TokenProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required bytes identifier = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_identifier();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes password = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required string kind = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_kind();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.TokenProto.kind");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // required string service = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_service();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.TokenProto.service");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TokenProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.TokenProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required bytes identifier = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_identifier(), target);
  }

  // required bytes password = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_password(), target);
  }

  // required string kind = 3;
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_kind().data(), static_cast<int>(this->_internal_kind().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.TokenProto.kind");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_kind(), target);
  }

  // required string service = 4;
  if (cached_has_bits & 0x00000008u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_service().data(), static_cast<int>(this->_internal_service().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.TokenProto.service");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_service(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.TokenProto)
  return target;
}

size_t TokenProto::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:hadoop.common.TokenProto)
  size_t total_size = 0;

  if (_internal_has_identifier()) {
    // required bytes identifier = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_identifier());
  }

  if (_internal_has_password()) {
    // required bytes password = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_password());
  }

  if (_internal_has_kind()) {
    // required string kind = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_kind());
  }

  if (_internal_has_service()) {
    // required string service = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service());
  }

  return total_size;
}
size_t TokenProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.TokenProto)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required bytes identifier = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_identifier());

    // required bytes password = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_password());

    // required string kind = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_kind());

    // required string service = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TokenProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TokenProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TokenProto::GetClassData() const { return &_class_data_; }


void TokenProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TokenProto*>(&to_msg);
  auto& from = static_cast<const TokenProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.TokenProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_identifier(from._internal_identifier());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_password(from._internal_password());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_kind(from._internal_kind());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_service(from._internal_service());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TokenProto::CopyFrom(const TokenProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.TokenProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TokenProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void TokenProto::InternalSwap(TokenProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.identifier_, lhs_arena,
      &other->_impl_.identifier_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.password_, lhs_arena,
      &other->_impl_.password_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.kind_, lhs_arena,
      &other->_impl_.kind_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.service_, lhs_arena,
      &other->_impl_.service_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata TokenProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[0]);
}

// ===================================================================

class CredentialsKVProto::_Internal {
 public:
  using HasBits = decltype(std::declval<CredentialsKVProto>()._impl_._has_bits_);
  static void set_has_alias(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::hadoop::common::TokenProto& token(const CredentialsKVProto* msg);
  static void set_has_token(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_secret(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::TokenProto&
CredentialsKVProto::_Internal::token(const CredentialsKVProto* msg) {
  return *msg->_impl_.token_;
}
CredentialsKVProto::CredentialsKVProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.CredentialsKVProto)
}
CredentialsKVProto::CredentialsKVProto(const CredentialsKVProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CredentialsKVProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.alias_){}
    , decltype(_impl_.secret_){}
    , decltype(_impl_.token_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.alias_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alias_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_alias()) {
    _this->_impl_.alias_.Set(from._internal_alias(), 
      _this->GetArenaForAllocation());
  }
  _impl_.secret_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.secret_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_secret()) {
    _this->_impl_.secret_.Set(from._internal_secret(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_token()) {
    _this->_impl_.token_ = new ::hadoop::common::TokenProto(*from._impl_.token_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.CredentialsKVProto)
}

inline void CredentialsKVProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.alias_){}
    , decltype(_impl_.secret_){}
    , decltype(_impl_.token_){nullptr}
  };
  _impl_.alias_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alias_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.secret_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.secret_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CredentialsKVProto::~CredentialsKVProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.CredentialsKVProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CredentialsKVProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.alias_.Destroy();
  _impl_.secret_.Destroy();
  if (this != internal_default_instance()) delete _impl_.token_;
}

void CredentialsKVProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CredentialsKVProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.CredentialsKVProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.alias_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.secret_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.token_ != nullptr);
      _impl_.token_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CredentialsKVProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string alias = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_alias();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.CredentialsKVProto.alias");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional .hadoop.common.TokenProto token = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes secret = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_secret();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CredentialsKVProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.CredentialsKVProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string alias = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_alias().data(), static_cast<int>(this->_internal_alias().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.CredentialsKVProto.alias");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_alias(), target);
  }

  // optional .hadoop.common.TokenProto token = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::token(this),
        _Internal::token(this).GetCachedSize(), target, stream);
  }

  // optional bytes secret = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_secret(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.CredentialsKVProto)
  return target;
}

size_t CredentialsKVProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.CredentialsKVProto)
  size_t total_size = 0;

  // required string alias = 1;
  if (_internal_has_alias()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alias());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000006u) {
    // optional bytes secret = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_secret());
    }

    // optional .hadoop.common.TokenProto token = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.token_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CredentialsKVProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CredentialsKVProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CredentialsKVProto::GetClassData() const { return &_class_data_; }


void CredentialsKVProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CredentialsKVProto*>(&to_msg);
  auto& from = static_cast<const CredentialsKVProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.CredentialsKVProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_alias(from._internal_alias());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_secret(from._internal_secret());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_token()->::hadoop::common::TokenProto::MergeFrom(
          from._internal_token());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CredentialsKVProto::CopyFrom(const CredentialsKVProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.CredentialsKVProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CredentialsKVProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_token()) {
    if (!_impl_.token_->IsInitialized()) return false;
  }
  return true;
}

void CredentialsKVProto::InternalSwap(CredentialsKVProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alias_, lhs_arena,
      &other->_impl_.alias_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.secret_, lhs_arena,
      &other->_impl_.secret_, rhs_arena
  );
  swap(_impl_.token_, other->_impl_.token_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CredentialsKVProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[1]);
}

// ===================================================================

class CredentialsProto::_Internal {
 public:
};

CredentialsProto::CredentialsProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.CredentialsProto)
}
CredentialsProto::CredentialsProto(const CredentialsProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CredentialsProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tokens_){from._impl_.tokens_}
    , decltype(_impl_.secrets_){from._impl_.secrets_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.CredentialsProto)
}

inline void CredentialsProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.tokens_){arena}
    , decltype(_impl_.secrets_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CredentialsProto::~CredentialsProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.CredentialsProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CredentialsProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tokens_.~RepeatedPtrField();
  _impl_.secrets_.~RepeatedPtrField();
}

void CredentialsProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CredentialsProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.CredentialsProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tokens_.Clear();
  _impl_.secrets_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CredentialsProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .hadoop.common.CredentialsKVProto tokens = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_tokens(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .hadoop.common.CredentialsKVProto secrets = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_secrets(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CredentialsProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.CredentialsProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .hadoop.common.CredentialsKVProto tokens = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_tokens_size()); i < n; i++) {
    const auto& repfield = this->_internal_tokens(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .hadoop.common.CredentialsKVProto secrets = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_secrets_size()); i < n; i++) {
    const auto& repfield = this->_internal_secrets(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.CredentialsProto)
  return target;
}

size_t CredentialsProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.CredentialsProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .hadoop.common.CredentialsKVProto tokens = 1;
  total_size += 1UL * this->_internal_tokens_size();
  for (const auto& msg : this->_impl_.tokens_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .hadoop.common.CredentialsKVProto secrets = 2;
  total_size += 1UL * this->_internal_secrets_size();
  for (const auto& msg : this->_impl_.secrets_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CredentialsProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CredentialsProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CredentialsProto::GetClassData() const { return &_class_data_; }


void CredentialsProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CredentialsProto*>(&to_msg);
  auto& from = static_cast<const CredentialsProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.CredentialsProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.tokens_.MergeFrom(from._impl_.tokens_);
  _this->_impl_.secrets_.MergeFrom(from._impl_.secrets_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CredentialsProto::CopyFrom(const CredentialsProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.CredentialsProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CredentialsProto::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(_impl_.tokens_))
    return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(_impl_.secrets_))
    return false;
  return true;
}

void CredentialsProto::InternalSwap(CredentialsProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tokens_.InternalSwap(&other->_impl_.tokens_);
  _impl_.secrets_.InternalSwap(&other->_impl_.secrets_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CredentialsProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[2]);
}

// ===================================================================

class GetDelegationTokenRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<GetDelegationTokenRequestProto>()._impl_._has_bits_);
  static void set_has_renewer(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

GetDelegationTokenRequestProto::GetDelegationTokenRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.GetDelegationTokenRequestProto)
}
GetDelegationTokenRequestProto::GetDelegationTokenRequestProto(const GetDelegationTokenRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetDelegationTokenRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.renewer_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.renewer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.renewer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_renewer()) {
    _this->_impl_.renewer_.Set(from._internal_renewer(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.GetDelegationTokenRequestProto)
}

inline void GetDelegationTokenRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.renewer_){}
  };
  _impl_.renewer_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.renewer_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetDelegationTokenRequestProto::~GetDelegationTokenRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.GetDelegationTokenRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetDelegationTokenRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.renewer_.Destroy();
}

void GetDelegationTokenRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetDelegationTokenRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.GetDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.renewer_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetDelegationTokenRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string renewer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_renewer();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "hadoop.common.GetDelegationTokenRequestProto.renewer");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetDelegationTokenRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.GetDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string renewer = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_renewer().data(), static_cast<int>(this->_internal_renewer().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "hadoop.common.GetDelegationTokenRequestProto.renewer");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_renewer(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.GetDelegationTokenRequestProto)
  return target;
}

size_t GetDelegationTokenRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.GetDelegationTokenRequestProto)
  size_t total_size = 0;

  // required string renewer = 1;
  if (_internal_has_renewer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_renewer());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetDelegationTokenRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetDelegationTokenRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetDelegationTokenRequestProto::GetClassData() const { return &_class_data_; }


void GetDelegationTokenRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetDelegationTokenRequestProto*>(&to_msg);
  auto& from = static_cast<const GetDelegationTokenRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.GetDelegationTokenRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_renewer()) {
    _this->_internal_set_renewer(from._internal_renewer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetDelegationTokenRequestProto::CopyFrom(const GetDelegationTokenRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.GetDelegationTokenRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetDelegationTokenRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void GetDelegationTokenRequestProto::InternalSwap(GetDelegationTokenRequestProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.renewer_, lhs_arena,
      &other->_impl_.renewer_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata GetDelegationTokenRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[3]);
}

// ===================================================================

class GetDelegationTokenResponseProto::_Internal {
 public:
  using HasBits = decltype(std::declval<GetDelegationTokenResponseProto>()._impl_._has_bits_);
  static const ::hadoop::common::TokenProto& token(const GetDelegationTokenResponseProto* msg);
  static void set_has_token(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::hadoop::common::TokenProto&
GetDelegationTokenResponseProto::_Internal::token(const GetDelegationTokenResponseProto* msg) {
  return *msg->_impl_.token_;
}
GetDelegationTokenResponseProto::GetDelegationTokenResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.GetDelegationTokenResponseProto)
}
GetDelegationTokenResponseProto::GetDelegationTokenResponseProto(const GetDelegationTokenResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetDelegationTokenResponseProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_token()) {
    _this->_impl_.token_ = new ::hadoop::common::TokenProto(*from._impl_.token_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.GetDelegationTokenResponseProto)
}

inline void GetDelegationTokenResponseProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}
  };
}

GetDelegationTokenResponseProto::~GetDelegationTokenResponseProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.GetDelegationTokenResponseProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetDelegationTokenResponseProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.token_;
}

void GetDelegationTokenResponseProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetDelegationTokenResponseProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.GetDelegationTokenResponseProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.token_ != nullptr);
    _impl_.token_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetDelegationTokenResponseProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .hadoop.common.TokenProto token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetDelegationTokenResponseProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.GetDelegationTokenResponseProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .hadoop.common.TokenProto token = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::token(this),
        _Internal::token(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.GetDelegationTokenResponseProto)
  return target;
}

size_t GetDelegationTokenResponseProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.GetDelegationTokenResponseProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .hadoop.common.TokenProto token = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.token_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetDelegationTokenResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetDelegationTokenResponseProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetDelegationTokenResponseProto::GetClassData() const { return &_class_data_; }


void GetDelegationTokenResponseProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetDelegationTokenResponseProto*>(&to_msg);
  auto& from = static_cast<const GetDelegationTokenResponseProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.GetDelegationTokenResponseProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_token()) {
    _this->_internal_mutable_token()->::hadoop::common::TokenProto::MergeFrom(
        from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetDelegationTokenResponseProto::CopyFrom(const GetDelegationTokenResponseProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.GetDelegationTokenResponseProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetDelegationTokenResponseProto::IsInitialized() const {
  if (_internal_has_token()) {
    if (!_impl_.token_->IsInitialized()) return false;
  }
  return true;
}

void GetDelegationTokenResponseProto::InternalSwap(GetDelegationTokenResponseProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.token_, other->_impl_.token_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetDelegationTokenResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[4]);
}

// ===================================================================

class RenewDelegationTokenRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<RenewDelegationTokenRequestProto>()._impl_._has_bits_);
  static const ::hadoop::common::TokenProto& token(const RenewDelegationTokenRequestProto* msg);
  static void set_has_token(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::TokenProto&
RenewDelegationTokenRequestProto::_Internal::token(const RenewDelegationTokenRequestProto* msg) {
  return *msg->_impl_.token_;
}
RenewDelegationTokenRequestProto::RenewDelegationTokenRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.RenewDelegationTokenRequestProto)
}
RenewDelegationTokenRequestProto::RenewDelegationTokenRequestProto(const RenewDelegationTokenRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RenewDelegationTokenRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_token()) {
    _this->_impl_.token_ = new ::hadoop::common::TokenProto(*from._impl_.token_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.RenewDelegationTokenRequestProto)
}

inline void RenewDelegationTokenRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}
  };
}

RenewDelegationTokenRequestProto::~RenewDelegationTokenRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.RenewDelegationTokenRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RenewDelegationTokenRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.token_;
}

void RenewDelegationTokenRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RenewDelegationTokenRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.RenewDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.token_ != nullptr);
    _impl_.token_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RenewDelegationTokenRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.TokenProto token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RenewDelegationTokenRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.RenewDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.TokenProto token = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::token(this),
        _Internal::token(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.RenewDelegationTokenRequestProto)
  return target;
}

size_t RenewDelegationTokenRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.RenewDelegationTokenRequestProto)
  size_t total_size = 0;

  // required .hadoop.common.TokenProto token = 1;
  if (_internal_has_token()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.token_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RenewDelegationTokenRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RenewDelegationTokenRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RenewDelegationTokenRequestProto::GetClassData() const { return &_class_data_; }


void RenewDelegationTokenRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RenewDelegationTokenRequestProto*>(&to_msg);
  auto& from = static_cast<const RenewDelegationTokenRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.RenewDelegationTokenRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_token()) {
    _this->_internal_mutable_token()->::hadoop::common::TokenProto::MergeFrom(
        from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RenewDelegationTokenRequestProto::CopyFrom(const RenewDelegationTokenRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.RenewDelegationTokenRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RenewDelegationTokenRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_token()) {
    if (!_impl_.token_->IsInitialized()) return false;
  }
  return true;
}

void RenewDelegationTokenRequestProto::InternalSwap(RenewDelegationTokenRequestProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.token_, other->_impl_.token_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RenewDelegationTokenRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[5]);
}

// ===================================================================

class RenewDelegationTokenResponseProto::_Internal {
 public:
  using HasBits = decltype(std::declval<RenewDelegationTokenResponseProto>()._impl_._has_bits_);
  static void set_has_newexpirytime(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

RenewDelegationTokenResponseProto::RenewDelegationTokenResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.RenewDelegationTokenResponseProto)
}
RenewDelegationTokenResponseProto::RenewDelegationTokenResponseProto(const RenewDelegationTokenResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RenewDelegationTokenResponseProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.newexpirytime_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.newexpirytime_ = from._impl_.newexpirytime_;
  // @@protoc_insertion_point(copy_constructor:hadoop.common.RenewDelegationTokenResponseProto)
}

inline void RenewDelegationTokenResponseProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.newexpirytime_){uint64_t{0u}}
  };
}

RenewDelegationTokenResponseProto::~RenewDelegationTokenResponseProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.RenewDelegationTokenResponseProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RenewDelegationTokenResponseProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RenewDelegationTokenResponseProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RenewDelegationTokenResponseProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.RenewDelegationTokenResponseProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.newexpirytime_ = uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RenewDelegationTokenResponseProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required uint64 newExpiryTime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_newexpirytime(&has_bits);
          _impl_.newexpirytime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RenewDelegationTokenResponseProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.RenewDelegationTokenResponseProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required uint64 newExpiryTime = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_newexpirytime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.RenewDelegationTokenResponseProto)
  return target;
}

size_t RenewDelegationTokenResponseProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.RenewDelegationTokenResponseProto)
  size_t total_size = 0;

  // required uint64 newExpiryTime = 1;
  if (_internal_has_newexpirytime()) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_newexpirytime());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RenewDelegationTokenResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RenewDelegationTokenResponseProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RenewDelegationTokenResponseProto::GetClassData() const { return &_class_data_; }


void RenewDelegationTokenResponseProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RenewDelegationTokenResponseProto*>(&to_msg);
  auto& from = static_cast<const RenewDelegationTokenResponseProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.RenewDelegationTokenResponseProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_newexpirytime()) {
    _this->_internal_set_newexpirytime(from._internal_newexpirytime());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RenewDelegationTokenResponseProto::CopyFrom(const RenewDelegationTokenResponseProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.RenewDelegationTokenResponseProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RenewDelegationTokenResponseProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void RenewDelegationTokenResponseProto::InternalSwap(RenewDelegationTokenResponseProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.newexpirytime_, other->_impl_.newexpirytime_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RenewDelegationTokenResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[6]);
}

// ===================================================================

class CancelDelegationTokenRequestProto::_Internal {
 public:
  using HasBits = decltype(std::declval<CancelDelegationTokenRequestProto>()._impl_._has_bits_);
  static const ::hadoop::common::TokenProto& token(const CancelDelegationTokenRequestProto* msg);
  static void set_has_token(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::hadoop::common::TokenProto&
CancelDelegationTokenRequestProto::_Internal::token(const CancelDelegationTokenRequestProto* msg) {
  return *msg->_impl_.token_;
}
CancelDelegationTokenRequestProto::CancelDelegationTokenRequestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hadoop.common.CancelDelegationTokenRequestProto)
}
CancelDelegationTokenRequestProto::CancelDelegationTokenRequestProto(const CancelDelegationTokenRequestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CancelDelegationTokenRequestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_token()) {
    _this->_impl_.token_ = new ::hadoop::common::TokenProto(*from._impl_.token_);
  }
  // @@protoc_insertion_point(copy_constructor:hadoop.common.CancelDelegationTokenRequestProto)
}

inline void CancelDelegationTokenRequestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.token_){nullptr}
  };
}

CancelDelegationTokenRequestProto::~CancelDelegationTokenRequestProto() {
  // @@protoc_insertion_point(destructor:hadoop.common.CancelDelegationTokenRequestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CancelDelegationTokenRequestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.token_;
}

void CancelDelegationTokenRequestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CancelDelegationTokenRequestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:hadoop.common.CancelDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.token_ != nullptr);
    _impl_.token_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CancelDelegationTokenRequestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .hadoop.common.TokenProto token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_token(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CancelDelegationTokenRequestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hadoop.common.CancelDelegationTokenRequestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .hadoop.common.TokenProto token = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::token(this),
        _Internal::token(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hadoop.common.CancelDelegationTokenRequestProto)
  return target;
}

size_t CancelDelegationTokenRequestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hadoop.common.CancelDelegationTokenRequestProto)
  size_t total_size = 0;

  // required .hadoop.common.TokenProto token = 1;
  if (_internal_has_token()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.token_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CancelDelegationTokenRequestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CancelDelegationTokenRequestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CancelDelegationTokenRequestProto::GetClassData() const { return &_class_data_; }


void CancelDelegationTokenRequestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CancelDelegationTokenRequestProto*>(&to_msg);
  auto& from = static_cast<const CancelDelegationTokenRequestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hadoop.common.CancelDelegationTokenRequestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_token()) {
    _this->_internal_mutable_token()->::hadoop::common::TokenProto::MergeFrom(
        from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CancelDelegationTokenRequestProto::CopyFrom(const CancelDelegationTokenRequestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hadoop.common.CancelDelegationTokenRequestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CancelDelegationTokenRequestProto::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_token()) {
    if (!_impl_.token_->IsInitialized()) return false;
  }
  return true;
}

void CancelDelegationTokenRequestProto::InternalSwap(CancelDelegationTokenRequestProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.token_, other->_impl_.token_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CancelDelegationTokenRequestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[7]);
}

// ===================================================================

class CancelDelegationTokenResponseProto::_Internal {
 public:
};

CancelDelegationTokenResponseProto::CancelDelegationTokenResponseProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hadoop.common.CancelDelegationTokenResponseProto)
}
CancelDelegationTokenResponseProto::CancelDelegationTokenResponseProto(const CancelDelegationTokenResponseProto& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CancelDelegationTokenResponseProto* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hadoop.common.CancelDelegationTokenResponseProto)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CancelDelegationTokenResponseProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CancelDelegationTokenResponseProto::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CancelDelegationTokenResponseProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Security_2eproto_getter, &descriptor_table_Security_2eproto_once,
      file_level_metadata_Security_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace hadoop
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hadoop::common::TokenProto*
Arena::CreateMaybeMessage< ::hadoop::common::TokenProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::TokenProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::CredentialsKVProto*
Arena::CreateMaybeMessage< ::hadoop::common::CredentialsKVProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::CredentialsKVProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::CredentialsProto*
Arena::CreateMaybeMessage< ::hadoop::common::CredentialsProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::CredentialsProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::GetDelegationTokenRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::GetDelegationTokenRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::GetDelegationTokenRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::GetDelegationTokenResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::GetDelegationTokenResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::GetDelegationTokenResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::RenewDelegationTokenRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::RenewDelegationTokenRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::RenewDelegationTokenRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::RenewDelegationTokenResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::RenewDelegationTokenResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::RenewDelegationTokenResponseProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::CancelDelegationTokenRequestProto*
Arena::CreateMaybeMessage< ::hadoop::common::CancelDelegationTokenRequestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::CancelDelegationTokenRequestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::hadoop::common::CancelDelegationTokenResponseProto*
Arena::CreateMaybeMessage< ::hadoop::common::CancelDelegationTokenResponseProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hadoop::common::CancelDelegationTokenResponseProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
