/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED! */
#ifndef __SOCKET_BPF_SKEL_H__
#define __SOCKET_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct socket_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_program *socket__filter_tcp;
	} progs;
	struct {
		struct bpf_link *socket__filter_tcp;
	} links;
};

static void
socket_bpf__destroy(struct socket_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
socket_bpf__create_skeleton(struct socket_bpf *obj);

static inline struct socket_bpf *
socket_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct socket_bpf *obj;
	int err;

	obj = (struct socket_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = socket_bpf__create_skeleton(obj);
	err = err ?: bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	socket_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct socket_bpf *
socket_bpf__open(void)
{
	return socket_bpf__open_opts(NULL);
}

static inline int
socket_bpf__load(struct socket_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct socket_bpf *
socket_bpf__open_and_load(void)
{
	struct socket_bpf *obj;
	int err;

	obj = socket_bpf__open();
	if (!obj)
		return NULL;
	err = socket_bpf__load(obj);
	if (err) {
		socket_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
socket_bpf__attach(struct socket_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
socket_bpf__detach(struct socket_bpf *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline int
socket_bpf__create_skeleton(struct socket_bpf *obj)
{
	struct bpf_object_skeleton *s;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)
		goto err;

	s->sz = sizeof(*s);
	s->name = "socket_bpf";
	s->obj = &obj->obj;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs)
		goto err;

	s->progs[0].name = "socket__filter_tcp";
	s->progs[0].prog = &obj->progs.socket__filter_tcp;
	s->progs[0].link = &obj->links.socket__filter_tcp;

	s->data_sz = 1840;
	s->data = (void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x30\x05\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x08\0\
\x01\0\xb7\0\0\0\0\0\0\0\x67\x02\0\0\x20\0\0\0\x77\x02\0\0\x20\0\0\0\x15\x02\
\x0a\0\0\0\0\0\x71\x11\0\0\0\0\0\0\x25\x01\x07\0\x3a\0\0\0\xb7\0\0\0\x01\0\0\0\
\xb7\x02\0\0\x01\0\0\0\x6f\x12\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\x10\x2c\
\0\x04\x5f\x12\0\0\0\0\0\0\x55\x02\x01\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\
\0\0\0\xbf\x16\0\0\0\0\0\0\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xfe\xff\xff\xff\xb7\
\x02\0\0\x0c\0\0\0\xb7\x04\0\0\x02\0\0\0\x85\0\0\0\x1a\0\0\0\xbf\x01\0\0\0\0\0\
\0\xb7\0\0\0\0\0\0\0\x6d\x10\x51\0\0\0\0\0\x69\xa1\xfe\xff\0\0\0\0\x55\x01\x4f\
\0\x08\0\0\0\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xe8\xff\xff\xff\xbf\x61\0\0\0\0\0\
\0\xb7\x02\0\0\x0e\0\0\0\xb7\x04\0\0\x14\0\0\0\x85\0\0\0\x1a\0\0\0\xbf\x01\0\0\
\0\0\0\0\xb7\0\0\0\0\0\0\0\x6d\x10\x46\0\0\0\0\0\x71\xa1\xf1\xff\0\0\0\0\x55\
\x01\x44\0\x06\0\0\0\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xd0\xff\xff\xff\xbf\x61\0\
\0\0\0\0\0\xb7\x02\0\0\x22\0\0\0\xb7\x04\0\0\x14\0\0\0\x85\0\0\0\x1a\0\0\0\xbf\
\x01\0\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x6d\x10\x3b\0\0\0\0\0\x69\xa1\xd2\xff\0\0\0\
\0\x15\x01\x02\0\x3f\xfb\0\0\x69\xa1\xd0\xff\0\0\0\0\x55\x01\x37\0\x3f\xfb\0\0\
\xb7\0\0\0\0\0\0\0\x7b\x0a\xc8\xff\0\0\0\0\x7b\x0a\xc0\xff\0\0\0\0\x7b\x0a\xb8\
\xff\0\0\0\0\x7b\x0a\xb0\xff\0\0\0\0\x7b\x0a\xa8\xff\0\0\0\0\x7b\x0a\xa0\xff\0\
\0\0\0\x7b\x0a\x98\xff\0\0\0\0\x7b\x0a\x90\xff\0\0\0\0\x7b\x0a\x88\xff\0\0\0\0\
\x7b\x0a\x80\xff\0\0\0\0\x7b\x0a\x78\xff\0\0\0\0\x7b\x0a\x70\xff\0\0\0\0\x7b\
\x0a\x68\xff\0\0\0\0\x7b\x0a\x60\xff\0\0\0\0\x7b\x0a\x58\xff\0\0\0\0\x61\x61\0\
\0\0\0\0\0\x69\xa2\xdc\xff\0\0\0\0\x77\x02\0\0\x02\0\0\0\x57\x02\0\0\x3c\0\0\0\
\xbf\x23\0\0\0\0\0\0\x07\x03\0\0\x29\0\0\0\x2d\x13\x20\0\0\0\0\0\x07\x02\0\0\
\x22\0\0\0\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\x58\xff\xff\xff\xbf\x61\0\0\0\0\0\0\
\xb7\x04\0\0\x07\0\0\0\x85\0\0\0\x1a\0\0\0\xbf\x01\0\0\0\0\0\0\xb7\x02\0\0\0\0\
\0\0\xb7\0\0\0\0\0\0\0\x6d\x12\x16\0\0\0\0\0\xb7\x01\0\0\x20\x25\x73\0\x63\x1a\
\x50\xff\0\0\0\0\x18\x01\0\0\x70\x61\x79\x6c\0\0\0\0\x6f\x61\x64\x3a\x7b\x1a\
\x48\xff\0\0\0\0\xbf\xa1\0\0\0\0\0\0\x07\x01\0\0\x48\xff\xff\xff\xbf\xa3\0\0\0\
\0\0\0\x07\x03\0\0\x58\xff\xff\xff\xb7\x02\0\0\x0c\0\0\0\x85\0\0\0\x06\0\0\0\
\x71\xa1\x58\xff\0\0\0\0\x25\x01\x08\0\x3a\0\0\0\x18\0\0\0\xff\xff\xff\xff\0\0\
\0\0\0\0\0\0\xb7\x02\0\0\x01\0\0\0\x6f\x12\0\0\0\0\0\0\x18\x01\0\0\0\0\0\0\0\0\
\0\0\x10\x2c\0\x04\x5f\x12\0\0\0\0\0\0\x55\x02\x01\0\0\0\0\0\xb7\0\0\0\0\0\0\0\
\x95\0\0\0\0\0\0\0\x70\x61\x79\x6c\x6f\x61\x64\x3a\x20\x25\x73\0\x47\x50\x4c\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\0\0\0\x04\0\xf1\xff\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x6c\0\0\0\0\0\x02\0\x70\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x73\0\0\0\0\0\x02\0\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7a\0\0\0\0\0\x03\0\
\xd0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x65\0\0\0\0\0\x03\0\x18\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x82\0\0\0\0\0\x03\0\xc8\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\0\0\
\0\x12\0\x02\0\0\0\0\0\0\0\0\0\x78\0\0\0\0\0\0\0\x0e\0\0\0\x12\0\x03\0\0\0\0\0\
\0\0\0\0\xd8\x02\0\0\0\0\0\0\x2f\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\
\0\0\0\x08\x09\0\x2e\x74\x65\x78\x74\0\x73\x6f\x63\x6b\x65\x74\0\x73\x6f\x63\
\x6b\x65\x74\x5f\x5f\x66\x69\x6c\x74\x65\x72\x5f\x74\x63\x70\0\x2e\x6c\x6c\x76\
\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x69\
\x73\x5f\x72\x65\x73\x70\x5f\x6d\x65\x73\x73\x61\x67\x65\0\x73\x6f\x63\x6b\x65\
\x74\x2e\x62\x70\x66\x2e\x63\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\
\x74\x61\x62\0\x4c\x42\x42\x31\x5f\x37\0\x4c\x42\x42\x30\x5f\x34\0\x4c\x42\x42\
\x30\x5f\x33\0\x4c\x42\x42\x31\x5f\x31\x32\0\x4c\x42\x42\x31\x5f\x31\x31\0\x2e\
\x72\x6f\x64\x61\x74\x61\x2e\x73\x74\x72\x31\x2e\x31\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x55\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x92\x04\0\0\0\0\0\0\x99\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\
\0\0\0\0\0\0\0\x78\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x07\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb8\0\0\0\0\0\0\0\
\xd8\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x8a\0\0\
\0\x01\0\0\0\x32\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x90\x03\0\0\0\0\0\0\x0c\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x30\0\0\0\x01\0\0\0\
\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9c\x03\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x21\0\0\0\x03\x4c\xff\x6f\0\0\0\
\x80\0\0\0\0\0\0\0\0\0\0\0\0\x90\x04\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\x07\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5d\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\xa0\x03\0\0\0\0\0\0\xf0\0\0\0\0\0\0\0\x01\0\0\0\x07\0\0\0\x08\0\
\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return -ENOMEM;
}

#endif /* __SOCKET_BPF_SKEL_H__ */
